### ISSUE TITLE
There is an ”algorithm type” entry, but no “algorithm”

### ISSUE THREAD

**Issue by dphilip** [enanomapper/ontologies#103]
While checking the ontology, I noticed that there is an ”algorithm type” entry, but no “algorithm”. 
Jia, can you please include it?
This should go under “information content entity” and all ”algorithm type” entries should go under it. Definition of “algorithm” can be taken from http://bioportal.bioontology.org/ontologies/IAO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000064

**Comment by JKChang2015** [comment]
Done:
Adding **algorithm**:  2038b7fbb1f55b7708ed79e603b9376a9926fdab
Relocate **algorithm type** to **algorithm**:  43e9740a43d7dac6caf7aa633f0b4ebc20381555
