### ISSUE TITLE
VIP scores incorrect entry

### ISSUE THREAD

**Issue by dphilip** [enanomapper/ontologies#105]
The "variable importance in projection scores" term in http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.enanomapper.org%2Fonto%2FENM_8000025
appears with a wrong name and not under "model-based regression" (http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.enanomapper.org%2Fonto%2FENM_8000017) as it should.

**Comment by JKChang2015** [comment]
![image](https://cloud.githubusercontent.com/assets/16242098/22466516/8a302cae-e7b8-11e6-9df6-b87849e413d4.png)

Fixed
