### ISSUE TITLE
SiO2 np correctly classified?

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#106]
![image](https://cloud.githubusercontent.com/assets/26721/22518483/0686d9e8-e8ad-11e6-83a6-238cf84b0fd8.png)

**Comment by JKChang2015** [comment]
https://github.com/enanomapper/ontologies/blob/master/config/chebi.iris#L51

I think I made the correction, but it seems something wrong with the slimming process.
also for 
https://github.com/enanomapper/ontologies/blob/master/config/chebi.iris#L12-L14

**Comment by G-Owen** [comment]
In ChEBI, chalcedony, diatomaceous earth, quartz, and vitreous silica are all forms of silicon dioxide, as is silicon dioxide nanoparticle. In ENM,  silicon dioxide nanoparticle should come under inorganic nanoparticle.

**Comment by G-Owen** [comment]
Which it does (at least it does in whatever version of ENM the OLS is using)!

**Comment by egonw** [comment]
The problem was that the config file was (strictly speaking) not valid... it uses a TAB to separate the IRI from the comment, where this should (strictly speaking) be a space. Slimmer is more relaxed now, and replaces any TAB with a space before further processing of the config line.

We'll see soon if this solves the problem...

**Comment by JKChang2015** [comment]
solved
