### ISSUE TITLE
should copper (II) oxide NP be a subclass of copper oxide NP?

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#107]
Now they are next to each other:

![image](https://cloud.githubusercontent.com/assets/26721/22520260/e198129e-e8b3-11e6-827a-1470e7f48925.png)

**Comment by JKChang2015** [comment]
@G-Owen

**Comment by G-Owen** [comment]
No it shouldn't! 
[There was an error in the ChEBI classification. 
Both cuprous oxide (CHEBI:81908, also known as copper(I) oxide) and copper(II) oxide (CHEBI:75955) are now child terms of copper oxide (CHEBI:134609).]

**Comment by G-Owen** [comment]
[The corresponding nanoparticles in ChEBI are  	
cuprous oxide nanoparticle (CHEBI:134402) and 
copper(II) oxide nanoparticle (CHEBI:83159)]

**Comment by JKChang2015** [comment]
close?

**Comment by G-Owen** [comment]
Sorry, I may have generated confusion here! When I said "no it shouldn't", I really meant "No, the terms  shouldn't be next to each other, unconnected. Yes copper(II) oxide NP should be a subclass of copper oxide"
Cuprous oxide (= copper(I) oxide) and cupric oxide (= copper(II) oxide) should both be subclasses of copper oxide.

**Comment by JKChang2015** [comment]
OK, I will have a look of these classes

**Comment by JKChang2015** [comment]
relocated & added.
