### ISSUE TITLE
graphene nanoplatelet missing

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#109]
As used in the NMSA abstract annotations. But I can live with "graphene nanoparticle"... the thing is a plate anyway...

**Comment by JKChang2015** [comment]
@G-Owen as CHEBI has graphene (CHEBI:36973), can we have a 'graphene nanoparticle' as well?

**Comment by egonw** [comment]
Yes, makes sense to me... just like we have ZnO nanoparticles made of ZnO: graphene nanoparticles made of graphene...

**Comment by G-Owen** [comment]
Now available: graphene nanoparticle (CHEBI:134404)

**Comment by egonw** [comment]
Not available on BioPortal.

**Comment by egonw** [comment]
Type in the patch.
