### ISSUE TITLE
add PAMAM dendrimer

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#110]
http://purl.bioontology.org/ontology/npo#NPO_965

**Comment by JKChang2015** [comment]
under chemical substance (http://purl.obolibrary.org/obo/CHEBI_59999) ?

**Comment by egonw** [comment]
I would say, under CHEBI:61483...

**Comment by JKChang2015** [comment]
material entity (http://purl.obolibrary.org/obo/BFO_0000040)
....⌞ environmental material (http://purl.obolibrary.org/obo/ENVO_00010483)
........⌞ organic material (http://purl.obolibrary.org/obo/ENVO_01000155)
............⌞mixture (http://livercancer.imbi.uni-heidelberg.de/ccont#CCONT_0000047)
...............⌞**dendritic polymer (http://purl.obolibrary.org/obo/CHEBI_61483)**
..................⌞**poly(amidoamine) dendrimer(http://purl.bioontology.org/ontology/npo#NPO_965)**
