### ISSUE TITLE
A549 is found twice in the ontology

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#111]
Once from EFO and once from the Brenda Tissue OBO (http://purl.obolibrary.org/obo/BTO_0000018)...

**Comment by JKChang2015** [comment]
Shall we keep the BTO one, since it has a better definition.

**Comment by egonw** [comment]
Sounds good to me... but for all cell lines then? If so, then we need to remove the cell line subtree from EFO

**Comment by JKChang2015** [comment]
I mean keep http://purl.obolibrary.org/obo/BTO_0000018 (A-549 cell)
and remove 
http://www.ebi.ac.uk/efo/EFO_0001086 (A549)

**Comment by JKChang2015** [comment]
removed： 96153a35c892c037b26ffa13d7bde87777f4455e
