### ISSUE TITLE
Missing JRC NM

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#116]
NM-212
NM-402
NM-403
NM-411
JRCNM10202a 
NM-600
NM-300K (silver)

Also check the list  
https://ec.europa.eu/jrc/sites/jrcsh/files/JRC%20Nanomaterials%20Repository-List%20of%20Representative%20Nanomaterials-201606.pdf

http://www.sciencedirect.com/science/article/pii/S027323001630229X

**Comment by egonw** [comment]
@vedina, I cannot find much info for NM-411 and only a NANoREG document...  the first JRC document you linked also does not have it...
