### ISSUE TITLE
Write up a Task for the NSC WG4 webpage

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#118]
![image](https://cloud.githubusercontent.com/assets/26721/23905194/8aa3a732-08ca-11e7-960c-0d82789b8789.png)

See https://www.nanosafetycluster.eu/working-groups/4-database-wg/tasks-2.html

**Comment by vedina** [comment]
https://www.nanosafetycluster.eu/working-groups/4-database-wg/tasks-2/2017-1.html

**Comment by egonw** [comment]
@vedina I do not seem to have an account anymore :(

**Comment by vedina** [comment]
Oh .. mine still works, pls send me the text, I'll upload
