### ISSUE TITLE
Adverse Outcome Pathway Ontology

### ISSUE THREAD

**Issue by pennym** [enanomapper/ontologies#119]
There is apparently a complete ontology for the AOPs being built. Could that be included in the eNanoMapper ontology? It doesn´t seem to be in the Bioportal yet...

https://github.com/DataSciBurgoon/aop-ontology

**Comment by egonw** [comment]
The paper is now published: http://www.authorcite.com/view.aspx?doi=10.1089/AIVT.2017.0012&mobileui=0&Key=/EEozN93N/kAxX5ysIRbuw

**Comment by egonw** [comment]
In progress: https://jenm.bigcat.maastrichtuniversity.nl/job/AOP/

**Comment by egonw** [comment]
ENM now includes MIE, AOP, AO, and KE.

**Comment by pennym** [comment]
Nice! But I guess it´s not online yet? Bioportal?

**Comment by egonw** [comment]
BioPortal has the released version. In the next week or two I will make a new release.
