### ISSUE TITLE
Add Mitsui MWCNT-7 under the term "multi-walled carbon nanotubes"

### ISSUE THREAD

**Issue by pennym** [enanomapper/ontologies#131]
I would recommend adding "MWCNT-7" to the "multi-walled carbon nanotubes" branch.
There are several ways of referring to this material, but the company itself and several studies, including the IARC monograph have used the above:
https://www.mitsui.com/us/en/release/2007/1214173_8227.html
https://particleandfibretoxicology.biomedcentral.com/articles/10.1186/1743-8977-11-4
http://www.thelancet.com/journals/lanonc/article/PIIS1470-2045%2814%2971109-X/fulltext#article_upsell

**Comment by vedina** [comment]
@pennym, I'd jump in with a more generic question (or proposal if you like) - shall the ontology contain manufacturer identifiers of nanomaterials, the same way as we have identifiers for JRC reference materials ? The JRC materials while widely used are far from the only ones.

**Comment by pennym** [comment]
Not sure, at the moment at least manufacturers will probably want to stay out of the scenery. Mitsui is an exception, because of that one widely used material. But I don´t propose adding Mitsui, but rather the MWCNT-7 term for the specific material that is so common in many studies. JRC is different and perhaps it would be better including institutes/organizations that provide reference/representative materials.

**Comment by vedina** [comment]
@pennym , do you think we should have NRCWE materials in the ontology as well ?

**Comment by pennym** [comment]
Why not, but maybe better ask NRCWE (Keld) first.
