### ISSUE TITLE
term corona missing

### ISSUE THREAD

**Issue by fredomatic** [enanomapper/ontologies#134]

**Comment by DeniseSl22** [comment]
The term corona seems to be missing from the developers version.
In which content should this term be added?
Is there any data related to this available? @fredomatic @egonw

**Comment by egonw** [comment]
https://bioportal.bioontology.org/ontologies/MESH?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FD000066970 could be an option, but we do not use MeSH at this moment.

**Comment by DeniseSl22** [comment]
Well, MeSH probably also has some overlap with the current ontology.... Would it be possible to compare the two (maybe based on name + fuzzy description first), and provide mappings to MeSH?
