### ISSUE TITLE
How should I know the parent location of a new ontology term?

### ISSUE THREAD

**Issue by marvinm2** [enanomapper/ontologies#137]
While following the [tutorial](https://github.com/enanomapper/tutorials/blob/master/Added%20ontology%20terms/README.md), I still find it difficult to pinpoint the location of where I should put a new term. Is there an overview of the ontology tree? Should I know the whole ontology to find the right location? Could there be a piece in the tutorial on specifically this issue?

**Comment by egonw** [comment]
That can be hard indeed... you need to understand the structure of the ontology enough to know what kind of thing you are looking at... the article is the best introduction at this moment.

**Comment by laurent2207** [comment]
Question answered
