### ISSUE TITLE
aluminium oxide nanoparticle 

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#139]
missing in https://bioportal.bioontology.org/ontologies/ENM 

strangely, in   http://specs.enanomapper.net/oecd/  there is

`aluminium oxide nanoparticles	ENM_9000005	http://purl.enanomapper.org/onto/ENM_9000005`

**Comment by egonw** [comment]
It exists indeed: https://github.com/enanomapper/ontologies/blob/3868c2ef8f0ef1df68384d53a58f42979294009e/internal/npo-ext.owl#L229-L235

It's not on BioPortal because there is a long overdue release :( BioPortal only shows the released version, not the development version.
