### ISSUE TITLE
mixture of nanoparticles

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#140]
Do we have / do we need  entry for `mixture of nanoparticles`  (there is a real database entry)

**Comment by egonw** [comment]
I'd just go for annotating with mixture...

**Comment by egonw** [comment]
And on an eNanoMapper side use the 'substance is one or more components" approach to indicate the components... and annotate each component with [NPO_707](http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2Fnpo%23NPO_707&jump_to_nav=true).

**Comment by vedina** [comment]
10x, the caveat is components are not given ...
