### ISSUE TITLE
EC1 ... EC100

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#143]
The NanoE-Tox data set uses basically ECxx where xx is any integer (in fact, floats too). BAO only has a selection of them.

**Comment by jmillanacosta** [comment]
- Create missing terms
- Fix current terms
- Round the floats? (10.5 -> 11)

**Comment by jmillanacosta** [comment]
ECxx equivalentClass : concentration response endpoint and ( has mode of action some activation) and ( has percent response some xx percent activation) and ( has mode of action only activation) and ( has percent response only xx percent activation)

for xx in 0-100, excluding  EC10, EC150(?), EC20, EC25, EC30, EC50, EC90 

Q: What is EC150 (http://www.bioassayontology.org/bao#BAO_0001236) ? Is it a mistake?

https://ontobee.org/ontology/catalog/BAO?iri=http://www.bioassayontology.org/bao%23BAO_0002162


![Image](https://github.com/enanomapper/ontologies/assets/83466805/69f815de-e08a-44e7-b3a4-7ed9271b959b)

**Comment by jmillanacosta** [comment]
Actually:
![image](https://github.com/enanomapper/ontologies/assets/83466805/d0d7c6ef-5aab-4d8d-bcc0-bf39e60dd7a2)
All of these classes are already being imported downstream of endpoint

https://github.com/enanomapper/ontologies/blob/cff3f07f30f2779115d97d39f38f9ef49ea0a5f9/config/bao.iris#L2 

Which means that the internal class for EC10 http://purl.enanomapper.org/onto/ENM_0000051 needs to be removed
