### ISSUE TITLE
impurities annotation

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#156]
What would be the recommended ontology entry to annotate impurities (obtained by different  methods, e.g. ICP-OES )

btw there is a typo in  [composizion_ICP-OES](https://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.enanomapper.org%2Fonto%2FENM_8000243)
as well as in
- `COMET - sistemic genotox`
- `elemental compostion_CHN analys`
- `Impedence_flow cytom`

What I am looking is  a generic term for `elemental composition` , on the level of `Granulometry`  for size.  Specific assays as in the enanomapper ontology are then used to annotated the method used.

- Found [composition entry](https://bioportal.bioontology.org/ontologies/ENM?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C53414), which is however subclass of `medium`.

**Comment by egonw** [comment]
Please do feel free to make typo fixes directly!
