### ISSUE TITLE
CITO: citation ontology

### ISSUE THREAD

**Issue by jannahastings** [enanomapper/ontologies#16]
investigate for inclusion

**Comment by egonw** [comment]
Cito:citesAsDatasource will be useful, but I suggest to pull in cito:cites and children...

**Comment by jannahastings** [comment]
As this ontology is mainly object properties with no significant classes, using it will need to wait until we have successfully implemented object properties in the Slimmer library.

**Comment by egonw** [comment]
@JKChang2015 properties are now supported... may I request pulling in cito:cites and children?

http://www.sparontologies.net/ontologies/cito/source.html

**Comment by JKChang2015** [comment]
OK

**Comment by egonw** [comment]
@laurent2207, can you please see to it that you add the following CiTO predicate `cito:cites` and children to the ontology with the new ROBOT approach?

**Comment by laurent2207** [comment]
https://jenkins.bigcat.unimaas.nl/job/eNanoMapper%20-%20CiTo%20-%20properties/

Could you (@egonw) check if the output file is the one you want. A lot of descendants in my opinion. If it alright I will add it to auto-dev

**Comment by egonw** [comment]
Looks good!
