### ISSUE TITLE
Linking to an ontology URI

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#164]
Looking for user friendly way to find ontology description by ontology URI 
e.g. is there easy way to demonstrate what `http://purl.enanomapper.org/onto/ENM_8000038`  means? Can't find searching by URI in Bioportal and AberOwl.  

- without downloading the entire (set of ) ontology and setting up own solution , just linking to existing resource.

**Comment by egonw** [comment]
During eNanoMapper we indeed have a SPARQL endpoint for this. But I will explore APIs... I'd reckon there must be something simple for this...

**Comment by vedina** [comment]
>  And click any of the "Full Ontology URI" links.

The "Full Ontology URI" are not the purl links, but Bioportal , hand crafted.  I'd like to avoid generating Bioportal links in code, when more than one ontology is involved. Wish the purl.enanomapper.net  links were resolvable ...

**Comment by vedina** [comment]
10x, will generate links as in the guidance

**Comment by gebele** [comment]
curl -H 'Accept: application/json' 'https://query.enanomapper.net/sparql/?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E+SELECT+DISTINCT+%2A+WHERE+%7B+%3Chttp%3A%2F%2Fpurl.enanomapper.org%2Fonto%2FENM_8000038%3E+%3Fp+%3Fo.%7D+LIMIT+100'
