### ISSUE TITLE
CHEBI_50828 & NPO_1373 should be the same

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#166]
silicon dioxide and silica is one and the same thing, there are two different entries, which is confusing
http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_50828

http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2Fnpo%23NPO_1373

**Comment by egonw** [comment]
Worse, they are not even in the same part of the ontology :(
