### ISSUE TITLE
WAXD / WAXS terms

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#181]
ENM_8000310  WAXD (Wide Angle X-ray Diffraction)   , no definition
synonym of WAXS http://purl.obolibrary.org/obo/CHMO_0000207

https://en.wikipedia.org/wiki/Wide-angle_X-ray_scattering

**Comment by laurent2207** [comment]
![image](https://user-images.githubusercontent.com/44968488/70629001-86dba580-1c29-11ea-8813-8d192d15273e.png)

Class is already in the .iris file?

**Comment by laurent2207** [comment]
Term added, will be in ENM with next release
