### ISSUE TITLE
HPRT - gene mutation base test

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#182]
do we have ontology entry for `HPRT - gene mutation base test` assay as well as [OECD 476 guideline](https://www.oecd-ilibrary.org/environment/test-no-476-in-vitro-mammalian-cell-gene-mutation-tests-using-the-hprt-and-xprt-genes_9789264264809-en) ?

**Comment by egonw** [comment]
Fixed by https://github.com/enanomapper/ontologies/pull/183
