### ISSUE TITLE
write down contacts (name, email) for all upstream ontologies

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#187]

**Comment by laurent2207** [comment]
Adverse Outcome Pathways Ontology (AOP):
- https://github.com/DataSciBurgoon/aop-ontology (no email available)

BioAssay Ontology (BAO):
- Stephan Schurer, sschurer@med.miami.edu

Basic Formal Ontology (BFO):
- Barry Smith, phismith@buffalo.edu

Cell Culture Ontology (CCONT):
- atthias Ganzinger, matthias.ganzinger@med.uni-heidelberg.de

Chemical Entities of Biological Interest (CHEBI):
- Gareth Owen, gowen@ebi.ac.uk

Chemical Information Ontology (CHEMINF):
- Egon Willighagen, egon.willighagen@maastrichtuniversity.nl

Chemical Methods Ontology (CHMO):
- Colin Batchelor, batchelorc@rsc.org

Experimental Factor Ontology (EFO):
- EFO User List, efo-users@ebi.ac.uk

Environment Ontology (ENVO):
- Pier Luigi Buttigieg, pbuttigi@mpi-bremen.de

FRBR-aligned Bibliographic Ontology (FABIO):
- Silvio Peroni, speroni@cs.unibo.it

Gene Ontology (GO):
- GO Helpdesk, https://github.com/geneontology/helpdesk/issues (no email available)

Human Physiology Simulation Ontology (HUPSON):
- Michaela Guendel, michaela.guendel@scai-extern.fraunhofer.de

Information Artifact Ontology (IAO):
- Alan Ruttenberg, alanruttenberg@gmail.com

National Cancer Institute Thesaurus (NCIT):
- NCICB Support, ncicbiit@mail.nih.gov

NanoParticle Ontology (NPO):
- Nathan Baker, nathan.baker@pnl.gov

Ontology of Adverse Events (OAE):
- Yongqun "Oliver" He, yongqunh@med.umich.edu

Ontology of Biological and Clinical Statistics (OBCS):
- Yongqun (Oliver) He, yongqunh@med.umich.edu
- Jie Zheng, jiezheng@upenn.edu

Ontology for Biomedical Investigations (OBI):
- Bjoern Peters, bpeters@liai.org

Phenotype And Trait Ontology (PATO):
- George Gkoutos, g.gkoutos@gmail.com

Semanticscience Integrated Ontology (SIO):
- Michel Dumontier, michel.dumontier@gmail.com

Unit Ontology (UO):
- George Gkoutos, g.gkoutos@gmail.com

**Comment by laurent2207** [comment]
Consider this done? @egonw
