### ISSUE TITLE
Merge 'toxicity' and 'toxicity endpoint' branches

### ISSUE THREAD

**Issue by jannahastings** [enanomapper/ontologies#20]
... favour the 'endpoint' parent as this is the way toxicologists think of toxicological categories

**Comment by vedina** [comment]
See page 21-22 at [Guidance Document on the Validation of (Quantitative) Structure-Activity Relationship [(Q)SAR] Models](http://www.oecd.org/publications/guidance-document-on-the-validation-of-quantitative-structure-activity-relationship-q-sar-models-9789264085442-en.htm] for the "defined endpoint" terminology.

**Comment by jannahastings** [comment]
When updating the NPO export, encountered an error in the resulting SLIM file: --  prefix not recognised ncicp -- something needs updating in the slimmer code? To investigate further.

**Comment by jannahastings** [comment]
Done.
