### ISSUE TITLE
[http://purl.enanomapper.org/onto/ENM_0000049] **Milling**

### ISSUE THREAD

**Issue by UanaF** [enanomapper/ontologies#200]
**What would you use as label or labels for the terms?**
Milling

**What is the definition of the term?**
The use of rotational cutting or grinding to reduce the size of a bulk material

**Is there an ontology that has this term?**
No, should be added in enanomapper ontology as new term; the ID is unique generated using Proteje.

**Additional context**
The term is added already in https://github.com/enanomapper/ontologies/blob/master/internal/npo-ext.owl based on the tutorial guidelines; defined as Web Ontology Language (OWL) class, and have an identifier, label, and superclass.

**Comment by vedina** [comment]
what about [CHMO_0001652](http://purl.obolibrary.org/obo/CHMO_0001652)

**Comment by laurent2207** [comment]
Closed this one because it was added? Or what is your question exactly @vedina ?

**Comment by vedina** [comment]
> Closed this one because it was added? Or what is your question exactly @vedina ?

This term exists in CHMO  (as many of the instrument / phys-chem measuring techniques) - my question is why not reusing ?

**Comment by laurent2207** [comment]
@UanaF has added this term. Good question btw! Will reopen and we should look into it.
