### ISSUE TITLE
Add National Cancer Institute Thesaurus to ontology

### ISSUE THREAD

**Issue by lrieswijk** [enanomapper/ontologies#21]
I noticed that a lot of new terms coming from a particular project are best reflected in NCIT. So it would be great if this ontology could be added to the eNanoMapper Ontology

**Comment by jannahastings** [comment]
It is not possible to add the full NCIT to eNanoMapper, as they have well over 250,000 entries which will totally overwhelm our small ontology! And most of those are not relevant to our domain anyway. Therefore I am closing this issue but will address specific requests for terms which can be logged separately.
