### ISSUE TITLE
protocol and assay type entries

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#22]
Could you point to eNanoMapper ontology entries to represent experimental protocol , or type of assay ; e.g. similar to 

* [EFO protocol](http://bioportal.bioontology.org/ontologies/EFO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000272)
* [OBI protocol](http://bioportal.bioontology.org/ontologies/OBI?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000272)
* [NPO physicochemical characterisation](http://bioportal.bioontology.org/ontologies/NPO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2Fnpo%23NPO_1356)  
* [BAO assay type](http://bioportal.bioontology.org/ontologies/BAO?p=classes&conceptid=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0002810)

**Comment by vedina** [comment]
Also could not find entries for  (physchem):

* Granulometry [CHMO granulometry](http://bioportal.bioontology.org/ontologies/CHMO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0002119)

* Partition coefficient [NCIT partition coefficient](http://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C20610) . There is logP descriptor  `CHEMINF_000251`  and logP endpoint `BAO_0002130`, but 
there is [difference](http://en.wikipedia.org/wiki/Partition_coefficient), but logP is the logarithm of the partitioning coefficient.

* would be nice to have an entry for `solubility in organic solvents` , which is OECD endpoint.   There is  already `solubility` and `water solubility`.

* is it (could it be) defined that `aqueous solubility` is synonym to `water solubility`

* [pH](http://en.wikipedia.org/wiki/PH) is defined in Unit Ontology `UO_0000196`  although it is a measurable physical [property](http://en.wikipedia.org/wiki/PH), no?

* crystallite http://en.wikipedia.org/wiki/Crystallite

* Aspect ratio [NPO aspect ratio](http://bioportal.bioontology.org/ontologies/NPO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2Fnpo%23NPO_1365)

* `surface area` - can't find neither [NPO](http://bioportal.bioontology.org/ontologies/NPO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2Fnpo%23NPO_1235)  not [CHEMINF](http://bioportal.bioontology.org/ontologies/CHEMINF?p=classes&conceptid=http%3A%2F%2Fsemanticscience.org%2Fresource%2FCHEMINF_000247)  

* [specific surface area](http://en.wikipedia.org/wiki/Specific_surface_area) is not the same as `surface area`

* [surface chemistry](http://bioportal.bioontology.org/ontologies/NCIT?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C64351)

* there is `catalytic activity unit` UO_0000119,  but not `catalytic activity`

**Comment by jannahastings** [comment]
(1) OBI's protocol added to OBI extract; 
(2) CHMO's granulometry added in new CHMO extract; 
(3) partition coefficient added to CHEMINF and extracted from there; 
(4) specific surface area and surface area included in CHEMINF and extracted from there; 
(5) for molecular weight, would it work to make this a synonym for the existing 'exact mass descriptor' which is included as CHEMINF_000217?
(6) solubility in water included from NPO, synonym aqueous solubility included in internal/npo-ext.owl, and solubility in organic solvents included in npo-ext.owl
(7) pH descriptor is included from CHEMINF
(8) crystallite is included in npo-ext.owl
(9) aspect ratio included from NPO
(10) I am not sure what you mean by surface chemistry, the link you give defines it as a measurement (so maybe 'surface chemistry assay'), but I am suspicious of that interpretation here, how is what you want different to 'surface coating' and 'surface functionalization of nanoparticle' which we have?
(11) catalytic activity is a GO term. I think we agreed not to include GO in enanomapper, we would just use it alongside. Is that OK?
(12) isoelectric point added from NPO
(13) size and all children, including diameter and area, added from PATO

Please note that some of the changes will not be visible until some outstanding issues with the slimmer are resolved. 

Please let me know what to do about the questions above (5, 10, 11). Thanks!

**Comment by vedina** [comment]
(5) Not sure if `exact mass descriptor` is relevant for nanomaterials .

(10)  [Example for silver nanoparticles](http://www.sigmaaldrich.com/materials-science/nanomaterials/silver-nanoparticles.html).  Also OECD HT  [Template 107 Nanomaterial surface chemistry](http://www.oecd.org/ehs/templates/oecdtemplate107nanomaterialsurfacechemistry.htm) contains information about NM surfaces (COATING, FUNCTIONALIZATION, FUNCTIONAL_GROUPS_TABLE, ATOMIC_COMPOSITION_TABLE) , as measured by methods specified in the template -   [XPS](http://goldbook.iupac.org/X06716.html) , [SIMS](http://goldbook.iupac.org/I03221.html) , [AES](https://en.wikipedia.org/wiki/Auger_electron_spectroscopy), etc. It may be different from surface coating' and 'surface functionalization of nanoparticle` in the sense that it specifies a encompassing category on the basis how these properties are measured.

(11) It may do, but not sure. Catalytic activity is defined in [GO](http://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0003824) as `Catalysis of a biochemical reaction`, while catalytic activity is not necessary about biochemical reaction (inorganic catalysis is a huge branch of chemical engineering!). The (OECD HT Template 113](http://www.oecd.org/ehs/templates/oecdtemplate113nanomaterialcatalyticactivity.htm) lists  the following methods  [DRIFTS](http://bioportal.bioontology.org/ontologies/CHMO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0000645) , Gas Chromatography, [ICPMS](http://bioportal.bioontology.org/ontologies/CHMO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0000538) , [TA](https://en.wikipedia.org/wiki/Temporal_analysis_of_products).  My understanding is [these](http://www.chem.qmul.ac.uk/surfaces/scc/) are not necessary involved with biochemical reactions. 


(Additional) Please add [Thermogravimetric analysis]( http://bioportal.bioontology.org/ontologies/CHMO?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0000690)

**Comment by jannahastings** [comment]
(10) a) 'surface chemistry assay' as a broad grouping class added to npo-ext.owl. 
        b) XPS already is 'x-ray photoelectron spectroscopy' CHMO:0000404 in Chemical Methods Ontology
        c) 'ion microscopy' is CHMO:0000097 from Chemical Methods Ontology
        d) 'auger electron spectroscopy' is CHMO:0000339 from Chemical Methods Ontology
(11) I agree that the definition restricts the GO term to biochemistry but I think the intended meaning of the term is broad enough that we can use it when we need to represent 'catalytic activity' rather than coining a new term with the same name (which will confuse users). The specific techniques should be represented separately as assays. 
      (a) DRIFTS CHMO:0000645 
      (b) gas chromatography NPO_1460
      (c) ICPMS CHMO:0000538
      (d) Thermogravimetric analysis added, CHMO:0000690

**Comment by fehrhart** [comment]
What of this is still actual?

**Comment by vedina** [comment]
if all the terms are added, then it might be closed

**Comment by fehrhart** [comment]
We will add:
solubility in organic solvents
partition coefficient
surface area

Then it should be completely done.
