### ISSUE TITLE
ENM-dev in Protégé

### ISSUE THREAD

**Issue by laurent2207** [enanomapper/ontologies#237]
**Opening in Protégé**
Could not get it to poen on the web version of Protégé, however that could be due to the webpage itself.
Could get it to open on the desktop version.

**General overview**
![image](https://user-images.githubusercontent.com/44968488/90521891-57434c80-e16b-11ea-9889-2784af6b408b.png)

**Issues**

**CHEBI**
CHEBI classes are not placed on the right spot, together with their child classes.
List of CHEBI classes:
* CHEBI_133326 - barium sulfate
* CHEBI_23367 - molecular entity
* CHEBI_27568 - selenium atom
* CHEBI_27638 - cobalt atom 
* CHEBI_28685 - molybdenum atom 
* CHEBI_31794 - magnesium oxide 
* CHEBI_33232 - application
* CHEBI_33341 - titanium atom
* CHEBI_33416 - fullerene 
* CHEBI_33893 - reagent
* CHEBI_51110 - copper(II) sulfide
* CHEBI_52855 - inorganic nanoparticle
* CHEBI_59999 - chemical substance
* CHEBI_60533 - γ-poly(L-glutamic acid) polymer 
* CHEBI_61483 - dendritic polymer
* CHEBI_85541 - bismuth cation

**information content entity, data item, data set and algorithm**
Information content entity is not put as a subclass of entity, subsequently data item (subclass of information content entity) and data set (subclass of data item) are also not placed right.

* information content entity (http://purl.obolibrary.org/obo/IAO_0000030),
subclass of: entity (http://purl.obolibrary.org/obo/BFO_0000001)

* data item (http://purl.obolibrary.org/obo/IAO_0000027), 
subclass of: information content entity (http://purl.obolibrary.org/obo/IAO_0000030)

* data set (http://purl.obolibrary.org/obo/IAO_0000100),
subclass of: data set

* Algorithm (http://purl.obolibrary.org/obo/IAO_0000064) and its child classes are also not put on the right spot.
subclass of: information content entity (http://purl.obolibrary.org/obo/IAO_0000030).

**Error1 - 'HPRT - gene mutation base test'**
HPRT - gene mutation base test is placed as a child class of Error1.
Can't seem to find 'HPRT - gene mutation base test' in ENM (bioportal) as well.

**Comment by laurent2207** [comment]
CHEBI part related to this issue: https://github.com/enanomapper/ontologies/issues/229

**Comment by vedina** [comment]
> HPRT - gene mutation base test is placed as a child class of Error1.
> Can't seem to find 'HPRT - gene mutation base test' in ENM (bioportal) as well.

Hypoxanthine Phosphoribosyl Transferase (HPRT) gene mutation assay   [OECD TG 476](https://www.oecd-ilibrary.org/docserver/9789264264809-en.pdf?expires=1597777517&id=id&accname=guest&checksum=973C0CDA84141593246746DEE54EDFDB)

**Comment by egonw** [comment]
@laurent2207, when loading the `-dev` version, I got the below warning. Did you get that too? It would explain a lot of problems you report:

![image](https://user-images.githubusercontent.com/26721/90602174-991ad400-e1f9-11ea-9af2-585dc33ee094.png)

**Comment by egonw** [comment]
Okay, it's not actually on Jenkins so that explains the missing file. I'm fixing that now, and will report what I get then.

**Comment by egonw** [comment]
> Hypoxanthine Phosphoribosyl Transferase (HPRT) gene mutation assay [OECD TG 476](https://www.oecd-ilibrary.org/docserver/9789264264809-en.pdf?expires=1597777517&id=id&accname=guest&checksum=973C0CDA84141593246746DEE54EDFDB)

I really need to write this up :/

**Comment by laurent2207** [comment]
> @laurent2207, when loading the `-dev` version, I got the below warning. Did you get that too? It would explain a lot of problems you report:
> 
> ![image](https://user-images.githubusercontent.com/26721/90602174-991ad400-e1f9-11ea-9af2-585dc33ee094.png)

No I did not get this warning. Did you use the desktop version of Protégé as well?

**Comment by egonw** [comment]
Yes, version 5.5. Well, I confirmed it is missing; fix pending.

**Comment by laurent2207** [comment]
> CHEBI part related to this issue: #229

Created pull request where atom and all child classes is made a child class of material entity. Hopefully this will fix the ChEBI issue

**Comment by egonw** [comment]
The HPRT issue is an interesting one. There are some rich axioms models, but I simplified it to just indicate the superclass.
