### ISSUE TITLE
Write Version 7 release notes

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#239]
Examples here: https://github.com/enanomapper/ontologies/releases

I suggest collecting changes we want to report in the comments. Then we can use that content later to write the changelog for the release.

**Comment by egonw** [comment]
* properties
* term from ACENano

**Comment by egonw** [comment]
Ack text: ACEnano - Analytical and Characterisation Excellence in nanomaterial risk assessment: A tiered approach (Grant Agreement 720952)

**Comment by egonw** [comment]
- removed HUPSON (only one term was used)

**Comment by laurent2207** [comment]
Version 7 of the eNanoMapper Ontology (ENM) was released on the XXth September 2020. ENM now covers XXXXX classes, compared with 12732 classes in version 7.

**Comment by laurent2207** [comment]
Work by EdelweissConnect?

**Comment by laurent2207** [comment]
@egonw please check release notes

Version 7 of the eNanoMapper Ontology (ENM) was released on the XXth February 2021. ENM now covers 11927 classes, compared with 12531 classes in version 6.

What's new in version 7

- Addition of properties from various ontologies, such as BAO, CHEMINF, NPO< RO and SIO (see also github issue [#240](https://github.com/enanomapper/ontologies/issues/240)).
- ACEnano - Analytical and Characterisation Excellence in nanomaterial risk assessment: A tiered approach (Grant Agreement 720952)
- Addition of more JRC materials, for more details see https://nanocommons.github.io/specifications/jrc/.
- Updated the GitHub repository with more granular permissions for easier community development.
- Removal of HUPSON slimmed ontology files as we used only one term. 
- Integration of EXPOSED terms by NanoinformaTIX team.

This release was made by the NanoCommons project which has received funding from European Union Horizon 2020 Programme (H2020) under grant agreement nº 731032. Full funding information is available at https://github.com/enanomapper/ontologies/blob/master/README.md

**Comment by vedina** [comment]
@laurent2207 EXPOSED 's official name is now MESOCOSM,  you may cite the paper https://doi.org/10.1016/j.impact.2020.100288

**Comment by laurent2207** [comment]
Ok added it! thanks.

**Comment by egonw** [comment]
@laurent2207, oh, please add this at the end: 

```
This release was made by the NanoCommons project which has received funding from European Union Horizon 2020 Programme (H2020) under grant agreement nº 731032. Full funding information is available at https://github.com/enanomapper/ontologies/blob/master/README.md
```

**Comment by laurent2207** [comment]
Is there already..

**Comment by egonw** [comment]
Argh... sorry :/

**Comment by laurent2207** [comment]
Release is done.
