### ISSUE TITLE
endpoints  to be added

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#24]
* NOAEL [No observed adverse effect level](http://goldbook.iupac.org/NT06911.html)
* LOAEL [Lowest-observed-adverse-effect level](http://goldbook.iupac.org/LT06909.html)
* LOEL [Lowest observed effect level](http://goldbook.iupac.org/L03634.html)
* NOEL [No observed effect level](http://goldbook.iupac.org/N04209.html)
* NOEC [No observed effect concentration](http://colowqforum.org/pdfs/whole-effluent-toxicity/03-2010/NOEC%20definition%20and%20dose%20response.pdf)
* RD50  (exposure concentration producing a 50% respiratory rate decrease) 
* EC10,  EC20, EC50, EC80,  EC90 ,EC100 [effective concentration] (http://bioportal.bioontology.org/ontologies/OBI?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001180)

**Comment by jannahastings** [comment]
Now done. 

EC30, EC50 already were there (from BAO). The other ECxx were added in the same location (i.e. beneath 'concentration response endpoint') and will be submitted back to BAO in due course. 

RD50 added as a subclass of RD50 and of 'toxicological endpoint'. 

NOAEL, LOAEL, LOEL, NOEL and NOEC added as subclasses of 'response endpoint'.
