### ISSUE TITLE
support for properties

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#240]
Extraction of properties need to be integrated on Jenkins. In Release 7 at least for the `NPO`.

**Comment by laurent2207** [comment]
For this release, this is done right? Or should we change the output files to {ONT}-slim-prop.owl in Jenkins jobs, run them again and then done? Or how do you want to do that?

**Comment by laurent2207** [comment]
Version 7 of the eNanoMapper Ontology (ENM) was released on the XXth September 2020. ENM now covers XXXXX classes, compared with 12732 classes in version 6.

**Comment by laurent2207** [comment]
Changed the output files to *-slim-prop.owl
