### ISSUE TITLE
Property "has_unit [SIO:000221]" not extracted in Jenkins job

### ISSUE THREAD

**Issue by laurent2207** [enanomapper/ontologies#243]
The property "has_unit [SIO:000221]" is not extracted in Jenkins job (https://jenkins.bigcat.unimaas.nl/job/eNanoMapper%20-%20SIO%20-%20properties/)

**Comment by egonw** [comment]
The URL of the term is wrong. Compare with the one for `has value`.

**Comment by laurent2207** [comment]
fixed
