### ISSUE TITLE
Connection refused in Jenkins job

### ISSUE THREAD

**Issue by laurent2207** [enanomapper/ontologies#245]
Connection refused in JEnkins job to /obo/iao.owl.

+ sh ./robot extract --method STAR --input cheminf.owl --term http://semanticscience.org/resource/CHEMINF_000200 --output cheminf-slim.owl
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/iao.owl> Cause: Connection refused (Connection refused)

**Comment by laurent2207** [comment]
lines of owl:import in cheminf.owl

xmlns:obo="http://purl.obolibrary.org/obo/"

<owl:imports rdf:resource="&obo;iao.owl"/>

is this correct?

**Comment by egonw** [comment]
Yes, looks fine. I had problems earlier with some ontology using `owl:import` with FTP, which is blocked. This is my lead, but did not have time today yet to confirm.

**Comment by laurent2207** [comment]
Okay, it is strange because when you open the hyperlink you get the owl file in your browser..?

**Comment by egonw** [comment]
@laurent2207, for which job was this? The CHEMINF one, right?

I just fixed it. It indeed was the proxy thing. Check the configuration of the job and check the new export line I added just before the robot call.

So, I think this issue is closed, but please check the slimmed file, which has way too much content, including stuff from BFO and several classes.

**Comment by laurent2207** [comment]
It is possible that more info is extracted. The STAR method will extract everything related to the property to make it logical

**Comment by laurent2207** [comment]
We can change it to the TOP method?

BOT: The BOT, or BOTTOM, -module contains mainly the terms in the seed, plus all their super-classes and the inter-relations between them. The module is called BOT (or BOTTOM) because it takes a view from the BOTTOM of the class-hierarchy upwards. Modules of this type are typically of a medium size and should be used if there is a need to include all super-classes in the module. This is the most widely used module type - when in doubt, use this one.

TOP: The TOP-module contains mainly the terms in the seed, plus all their sub-classes and the inter-relations between them. The module is called TOP because it takes a view from the TOP of the class-hierarchy downwards. Modules of this type are typically large and should only be used if there is a need to include all sub-classes in the module.

STAR: The STAR-module contains mainly the terms in the seed and the inter-relations between them (not necessarily sub- and super-classes). Modules of this type are typically very small and should be used if the module needs to be of minimal size containing only (or mostly) the classes in the seed file.

**Comment by laurent2207** [comment]
Decided to use STAR method. Jenkins job works.
