### ISSUE TITLE
Incorporation of several URIs from new and already used ontology resources

### ISSUE THREAD

**Issue by lrieswijk** [enanomapper/ontologies#25]
We stumbled across some URIs that need to be incorporated in the ENM ontology. Mentioned below are the ontology source and then the respective URIs.

ADW:
Measurement_units

BAO:
BAO_0000520

CRISP:
3091-4941

CSEO
Exposure_Concentration

EFO:
EFO_0001444
EFO_0005067

GO:
GO_0009293

HUPSON:
hupson:SCAIVPH_00000886
hupson:SCAIVPH_00000190
hupson:SCAIVPH_00000392

IAO:
IAO_0000301

NCIT:
C119826
C17941
C25169
C25284
C25365
C25492
C25572
C25625
C25681
C38389
C42651
C42721
C43531
C44473
C45805
C46003
C50400
C54166
C61299
C61412
C68553
C68806
C71477
C80514
C83039
C88214
C16866
C18189
C25209
C25212
C25246
C25247
C25474
C25666
C33177
C41130
C42614
C42680
C42709
C43530
C45518
C48041
C48937
C49507
C52478
C53321
C62352
C70766
C90446
C25474

NIF:
nlx_res_090901

NPO:
NPO_1517
NPO_1167
NPO_1344
NPO_1345
NPO_1364
NPO_1573
NPO_1812
NPO_1818
NPO_1853

OBI:
OBI_0000272
OBI_0000835
OBI_0000984
OBI_0001152
OBI_0001185
OBI_0000018
OBI_0000031
OBI_0001876
OBI_0100026

PATO:
PATO_0000011
PATO_0000068
PATO_0000165
PATO_0002175
PATO_0000117
PATO_0000052
PATO_0000122
PATO_0000146
PATO_0000918
PATO_0000921
PATO_0001334
PATO_0001555

SNOMEDCT:
4601000
46595003
246093002
261586004
277046005
304889007

**Comment by lrieswijk** [comment]
@jannahastings and @G-Owen have these URIs already been added to the ENM ontology?

**Comment by jannahastings** [comment]
1. ADW-measurement unit --> not including this as we already have 'unit' from the Unit Ontology with all relevant units of measure there.

2. BAO_0000520 added to the BAO import

**Comment by lrieswijk** [comment]
Is it possible that the SNOMEDCT and NCIT terms are also added to the eNM ontology @G-Owen ?

**Comment by lrieswijk** [comment]
This patch add "organism" from the OBI ontology: https://github.com/enanomapper/slimmer/pull/24

**Comment by egonw** [comment]
PR in https://github.com/enanomapper/slimmer/pull/27

**Comment by lrieswijk** [comment]
This patch add "transduction" from GO ontology: https://github.com/enanomapper/slimmer/pull/25

**Comment by lrieswijk** [comment]
This patch add "age" from PATO ontology https://github.com/enanomapper/slimmer/pull/26

**Comment by lrieswijk** [comment]
This patch add "batch number" from NCIT ontology https://github.com/enanomapper/slimmer/pull/28
