### ISSUE TITLE
purl broken

### ISSUE THREAD

**Issue by janelomax** [enanomapper/ontologies#255]
I'm getting an error for your purl:

http://purl.enanomapper.net/onto/enanomapper.owl

"This site can’t be reached"

thanks

**Comment by egonw** [comment]
Dear @janelomax, sorry for the late reply. I do not have control over this domain (it was done by another eNanoMapper partner).

Please use this URL: http://enanomapper.github.io/ontologies/enanomapper.owl

And let me know if that works for you (it should).

**Comment by laurent2207** [comment]
Can we close this one?

**Comment by janelomax** [comment]
yep, thanks!
