### ISSUE TITLE
[TERM REQUEST] HPAEC 

### ISSUE THREAD

**Issue by ammar257ammar** [enanomapper/ontologies#258]
**What would you use as label or labels for the terms?**
HPAEC (Human pulmonary artery endothelial cell line)

**What is the definition of the term?**
Human pulmonary artery endothelial cell line

**Is there an ontology that has this term?**
BTO:0003151

**Additional context**
None

**Comment by laurent2207** [comment]
Added term as sub class of _cell line_ (http://www.ebi.ac.uk/efo/EFO_0000322)
