### ISSUE TITLE
[TERM REQUEST] Alveolar macrophage

### ISSUE THREAD

**Issue by ammar257ammar** [enanomapper/ontologies#259]
**What would you use as label or labels for the terms?**
Circulating macrophages and tissue macrophages (alveolar macrophages) of lung

**What is the definition of the term?**
Circulating macrophages and tissue macrophages (alveolar macrophages) of lung

**Is there an ontology that has this term?**
CL:1001603 (Cell ontology)
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_1001603 

**Additional context**
None

**Comment by laurent2207** [comment]
Added term to ontology, will be in next release
