### ISSUE TITLE
[TERM REQUEST] bone marrow mononuclear cell

### ISSUE THREAD

**Issue by ammar257ammar** [enanomapper/ontologies#260]
**What would you use as label or labels for the terms?**
(BMM) bone marrow mononuclear cell

**What is the definition of the term?**
A mononuclear cell that is part_of a bone marrow.

**Is there an ontology that has this term?**
CL:0010004 (Cell ontology)
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0010004

**Additional context**
None

**Comment by laurent2207** [comment]
Added term to ontology, will be in next release
