### ISSUE TITLE
[TERM REQUEST] peripheral blood mononuclear cell

### ISSUE THREAD

**Issue by ammar257ammar** [enanomapper/ontologies#261]
**What would you use as label or labels for the terms?**
(PBMC) peripheral blood mononuclear cell

**What is the definition of the term?**
A mixture of monocytes and lymphocytes; blood leucocytes from which granulocytes have been separated and removed

**Is there an ontology that has this term?**
BTO:0001025 (BRENDA tissue ontology)
https://www.ebi.ac.uk/ols/ontologies/bto/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBTO_0001025

**Additional context**
None

**Comment by laurent2207** [comment]
Added term to ontology, will be in next release
