### ISSUE TITLE
[TERM REQUEST] monocyte-derived dendritic cell

### ISSUE THREAD

**Issue by ammar257ammar** [enanomapper/ontologies#262]
**What would you use as label or labels for the terms?**
(MDDC) monocyte-derived dendritic cell

**What is the definition of the term?**
monocyte-derived dendritic cell

**Is there an ontology that has this term?**
BTO:0002900 (BRENDA tissue ontology)
https://www.ebi.ac.uk/ols/ontologies/bto/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBTO_0002900

**Additional context**
None

**Comment by laurent2207** [comment]
Added term to ontology, will be in next release
