### ISSUE TITLE
[TERM REQUEST] Mixture of nanomaterials

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#264]
**What would you use as label or labels for the terms?**
Labels are short names of the term, as you would use them in written text.

**What is the definition of the term?**
Not an expert, but the term is used in the literature, e.g. https://doi.org/10.1016/j.scitotenv.2018.04.180 

**Is there an ontology that has this term?**
CHEBI_60004 definition 'A mixture is a chemical substance composed of multiple molecules, at least two of which are of a different kind.' - not sure if it applies to mixture of nanomaterials

**Additional context**
Need to annotate a data entry coming from exposure studies, and named as "mixture of nanomaterials"

**Comment by egonw** [comment]
Added http://purl.obolibrary.org/obo/CHEBI_60004 mixture
