### ISSUE TITLE
[TERM REQUEST] Isothermal titration calorimetry (ITC)

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#265]
**What would you use as label or labels for the terms?**
Isothermal titration calorimetry 
ITC

**What is the definition of the term?**
https://en.wikipedia.org/wiki/Isothermal_titration_calorimetry

**Is there an ontology that has this term?**
http://www.bioassayontology.org/bao#BAO_0000428

**Additional context**
performed in NANoREG2

**Comment by laurent2207** [comment]
Already added by Gergana
