### ISSUE TITLE
[TERM REQUEST] OECD 490

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#266]
**What would you use as label or labels for the terms?**
MLA-TK
OECD 490

**What is the definition of the term?**
https://www.oecd.org/publications/test-no-490-in-vitro-mammalian-cell-gene-mutation-tests-using-the-thymidine-kinase-gene-9789264264908-en.htm

**Is there an ontology that has this term?**
could not find

**Additional context**
Used in some nanosafety projects

**Comment by laurent2207** [comment]
We can add this term to the list of OECD guidelines we already have. http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C17564

Maybe an idea to include a subclass of Guidelines, named OECD guidelines or something similar and make all those guidelines a subclass of.

**Comment by vedina** [comment]
> We can add this term to the list of OECD guidelines we already have. http://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C17564
> 

thanks !

> Maybe an idea to include a subclass of Guidelines, named OECD guidelines or something similar and make all those guidelines a subclass of.

Yes, ideally this should accommodate also standard protocols like ISO , CEN and national ones like DIN, BST etc

**Comment by laurent2207** [comment]
Entered this report in Wikidata (https://www.wikidata.org/wiki/Q103983010)

**Comment by laurent2207** [comment]
https://github.com/enanomapper/ontologies/pull/267 See pull request to add term to ENM

**Comment by laurent2207** [comment]
Pull request merge will create new issue for including a subclass of Guidelines, named OECD guidelines or something similar and make all those guidelines a subclass of.
