### ISSUE TITLE
Looking for best match for LDH cytotoxicity assay

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#27]
Could someone (@fehrhart @lrieswijk ?) please help with suggesting the correct ontology (BAO?) entry for the following two assays:

* Cell viability - cell membrane damage: Lactate dehydrogenase assay (LDH)  (CytoTox 96® Non-radioactive cytotoxicity assay - Promega, G1780) 
* TNF-α released by primary human macrophages in the culture medium was measured using ELISA kit following the instructions provided by the manufacturer (MABTECH, 3510-1A-20). 

Both used in [doi:10.1371/journal.pone.0127174](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0127174)

**Comment by egonw** [comment]
cc @bartsmeets

**Comment by egonw** [comment]
LDH may actually not be in there yet... it's one of the assay types in the NanoWiki data (see the deliverable). I think we need to make a subclassof http://www.bioassayontology.org/bao#BAO_0000167 ..

**Comment by egonw** [comment]
Yes, because we don't have (eNanoMapper) URIs for either assay yet...

**Comment by vedina** [comment]
Is it possible to suggest a related entry for the second assay (even if not exactly the same)?

**Comment by lrieswijk** [comment]
We found a potential URI within BioPortal originating from NanoParticle
Ontology. See details below. The CytoTox 96 is just a brand name for a
commercially available kit to measure LDH activity which is sold by
Promega.

Preferred Name

LDH release assay
Synonyms

LDH assay

lactate dehydrogenase assay
Definitions

<ncicp:ComplexDefinition xmlns:ncicp="
http://ncicb.nci.nih.gov/xml/owl/EVS/ComplexProperties.xsd#"><ncicp:def-definition>A
cell viability assay which is performed by assessing the activity of
lactate dehydrogenase (a cytoplasmic enzyme) released into the cell culture
supernatant, when the plasma membrane is damaged. LDH release is used as a
marker of dead
cells.</ncicp:def-definition><ncicp:Definition_Review_Date>100430</ncicp:Definition_Review_Date><ncicp:def-source>NPO</ncicp:def-source><ncicp:Definition_Reviewer_Name>Dennis
Thomas</ncicp:Definition_Reviewer_Name></ncicp:ComplexDefinition>
ID

http://purl.bioontology.org/ontology/npo#NPO_1709
code

NPO_1709
definition

A cell viability assay which is performed by assessing the activity of
lactate dehydrogenase (a cytoplasmic enzyme) released into the cell culture
supernatant, when the plasma membrane is damaged. LDH release is used as a
marker of dead cells.100430NPODennis Thomas
label

LDH release assay
preferred_name

LDH release assay
prefixIRI

npo:NPO_1709
synonym

LDH assay

lactate dehydrogenase assay
subClassOf

cell viability assay
<http://bioportal.bioontology.org/ontologies/NPO?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2Fnpo%23NPO_1708>





2015-07-20 11:59 GMT+02:00 ngn <notifications@github.com>:

**Comment by vedina** [comment]
Thanks @lrieswijk !

**Comment by egonw** [comment]
Is the term added to the eNanoMapper ontology too now, then?

**Comment by vedina** [comment]
Oops, not that I am aware of, reopening.

**Comment by lrieswijk** [comment]
For the TNF-alpha assay we also made a suggestion:
http://purl.bioontology.org/ontology/SNOMEDCT/84861005 -->

Tumor necrosis factor assay

2015-07-21 9:40 GMT+02:00 ngn <notifications@github.com>:

**Comment by jannahastings** [comment]
LDH release assay from NPO now added to eNanoMapper ontology. Sorry for the delay. 

It is not possible at the moment to import content from SNOMED-CT, so I have manually added 'tumor necrosis assay' which is now ENM_9000011.
