### ISSUE TITLE
Terms mapping 

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#28]
Please help mapping these terms to ontology entries - could be one or more annotation per term.

`aids used to disperse/sonification`
`aids used to disperse/stirring`
`aids used to disperse/vortexing`
`cell culture conditions - medium`
`cell culture conditions - serum`
`cell culture conditions - serum concentration in growth medium`
`cell culture conditions - serum concentration in treatment medium`
`cell line/type - full name`
`cell line/type - short name`
`cell line/type - supplier`
`dispersion agent`
`dispersion protocol`
`concentration`
`time point`
`replicate`

@lrieswijk 
@bartsmeets 
@egonw

**Comment by lrieswijk** [comment]
Hi,

Freddie and I had a look at the terms and made some suggestions:


Sonication (same as sonification) -->  in ENM ontology npo:NPO_1961


Vortexing --> in ENM ontology synonym vortex shaking npo:NPO_1952


Stirring request should be made in GitHub -->  CHMO:0002774


Some suggestions for the cell culture terms:

https://docs.google.com/spreadsheets/d/1oqlLdL9m60j4VEoiKV-ebgpLxZH5MjxKUwHYcKGyy58/edit#gid=903550541


Dispersion agent --> Is it meant here a medium or a solvent? Or a kind of
chemical dispersion stabilizer?


Add a subclass to dispersion --> protocol= OBI:0000272

Hope this helps!

Linda and Freddie

2015-07-21 8:12 GMT+02:00 ngn <notifications@github.com>:

**Comment by lucfar** [comment]
Dispersion agent = Bovine Serum Albumin solution 0.05% in water.

Hope this is fine./ Lucian

**Comment by fehrhart** [comment]
Dear Lucian, dear Nina,

 the term "dispersion agent" is currently not mapped to any ontology - at
least not in a way we could use it.

We propose to write a new one and add it as a subclass of "dispersion":

preferred name: dispersion agent
synonym: dispersant, dispersing agent
definition: A *dispersant* or a *dispersing agent* is either a non-surface
active polymer <https://en.wikipedia.org/wiki/Polymer> or a surface-active
substance <https://en.wikipedia.org/wiki/Surfactant> added to a suspension
<https://en.wikipedia.org/wiki/Suspension_%28chemistry%29>, usually a
colloid <https://en.wikipedia.org/wiki/Colloid>, to improve the separation
of particles <https://en.wiktionary.org/wiki/Particles> and to prevent
settling <https://en.wikipedia.org/wiki/Settling> or clumping
<https://en.wiktionary.org/wiki/clumping>.  (Source: Wikipedia)


Best regards,
Freddie & Linda

**Comment by fehrhart** [comment]
Dispersion agent will be added - but in superclass "chemical substance"
