### ISSUE TITLE
Error from ROBOT when loading enanomapper.owl - Problem parsing chebi-ext.owl 

### ISSUE THREAD

**Issue by markmcdowall** [enanomapper/ontologies#281]
Hi,

When loading the enanomapper.owl via http://enanomapper.github.io/ontologies/enanomapper.owl using ROBOT:

```
java -Xmx14G -jar bin/robot.jar merge -I http://enanomapper.github.io/ontologies/enanomapper.owl -o enanomapper.owl
```

I get the following error:

```
[Fatal Error] :24:17: XML document structures must start and end within the same entity.
Could not load imported ontology: <http://enanomapper.github.io/ontologies/internal/chebi-ext.owl> Cause: Problem parsing http://enanomapper.github.io/ontologies/internal/chebi-ext.owl
```

In [chebi-ext.owl](https://github.com/enanomapper/ontologies/blob/master/internal/chebi-ext.owl) it looks like it is missing a `</rdf>` at the end of the file

**Comment by egonw** [comment]
@markmcdowall, thank you for your report. In parallel we found that some of the `*.ext.owl` files were not well-formed. I had not seen your report at the time, but it sounds like the same problem. We fixed this in https://github.com/enanomapper/ontologies/commit/baf55094c45e0da47cb76fd356b15b29d3aafb82

Can you please try again?

**Comment by markmcdowall** [comment]
Hi @egonw,

Thanks for the update. The file was able to download and get parsed successfully.

Cheers.

**Comment by egonw** [comment]
Happy to hear that!
