### ISSUE TITLE
[TERM REQUEST] Lattice energy

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#283]
**What would you use as label or labels for the terms?**
Lattice energy

**What is the definition of the term?**
The lattice energy of a crystalline solid is a measure of the energy released when ions are combined to make a compound. It is a measure of the cohesive forces that bind ions. Lattice energy is relevant to many practical properties including solubility, hardness, and volatility. The lattice energy is usually deduced from the Born–Haber cycle.[1]
[1] https://en.wikipedia.org/wiki/Lattice_energy

**Is there an ontology that has this term?**
could not find the term in Bioportal

**Additional context**
descriptor in material modelling

**Comment by laurent2207** [comment]
@vedina Possible to put this term as a subclass of [energetic descriptor? ](http://semanticscience.org/resource/CHEMINF_000016).

**Comment by vedina** [comment]
> @vedina Possible to put this term as a subclass of [energetic descriptor? ](http://semanticscience.org/resource/CHEMINF_000016).

Yes, this is correct

**Comment by laurent2207** [comment]
Term added see #285
