### ISSUE TITLE
update Jenkins to 1.0.2 or 1.0.3

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#289]
The Jenkins configurations still use 1.0.0, but that one has a bug. The configuration hardcodes the version and this needs updating. Example current config:

```
wget -nc https://github.com/enanomapper/slimmer/releases/download/v1.0.0/slimmer-1.0.0-jar-with-dependencies.jar
java -Dhttp.proxyHost=proxy.unimaas.nl -Dhttp.proxyPort=3128 -Dhttps.proxyHost=proxy.unimaas.nl -Dhttps.proxyPort=3128 -cp slimmer-1.0.0-jar-with-dependencies.jar com.github.enanomapper.Slimmer .
```

**Comment by laurent2207** [comment]
So just change the v1.0.0 and slimmer-1.0.0-jar to 1.0.2 or 1.0.3?

**Comment by egonw** [comment]
Yes, correct. Actually, 1.0.3 is not release yet, but 1.0.2 is: https://github.com/enanomapper/slimmer/releases/tag/v1.0.2 The link points to the binary included as "asset".

**Comment by laurent2207** [comment]
Done, changed it to 1.0.2 for now. Everything builds fine.
