### ISSUE TITLE
NOEC class in ENM ontology unsatisfiable

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#29]
From a private email:

    It seems that http://purl.enanomapper.org/onto/ENM_0000060 (NOEC, no
    observed effect concentration), is unsatisfiable when the ontology is
    classified. As a result, it currently shows up as a subclass of every
    class in ENM (since it becomes equivalent to owl:Nothing), which is
    probably not intended. It also is messing up [the] display of that
    class, which is a bug we'll fix soon (we'll show a list of all
    unsatisfiable classes instead and never include them in the treeview).

**Comment by leechuck** [comment]
To reproduce, open ENM in Protege and classify with ELK.

**Comment by egonw** [comment]
Mmm... not sure why this is... this is the RDF/XML for NOEC:

        <owl:Class rdf:about="http://purl.enanomapper.org/onto/ENM_0000060">
            <rdfs:label xml:lang="en">NOEC</rdfs:label>
            <rdfs:subClassOf rdf:resource="http://purl.enanomapper.org/onto/ENM_0000056"/>
            <rdfs:subClassOf rdf:resource="http://www.bioassayontology.org/bao#BAO_0002162"/>
            <rdfs:comment>This value is used, along with other factors, to determine toxicity limits in permits. </rdfs:comment>
            <obo:IAO_0000118>no observed effect concentration</obo:IAO_0000118>
            <obo:IAO_0000115>The highest concentration of a substance to which organisms are exposed that causes no observable adverse effect on the test organisms. </obo:IAO_0000115>
        </owl:Class>

**Comment by egonw** [comment]
Yes, the thing is confirmed not satisfiable: ENM_0000060 now (indirectly) subclasses two disjoint BAO classes: BAO_0000180 via BAO_0002162 and BAO_0000181 via ENM_0000056.

**Comment by egonw** [comment]
This issue needs further discussion with the BAO team.
