### ISSUE TITLE
purl link on website broken

### ISSUE THREAD

**Issue by laurent2207** [enanomapper/ontologies#290]
The [purl](http://purl.enanomapper.net/onto/enanomapper.owl) link on the [website](http://www.enanomapper.net/ontology) is broken.

This needs to be fixed.

**Comment by egonw** [comment]
I emailed DouglasConnect.

**Comment by egonw** [comment]
Got a reply, and replies to that with the suggested edits. particularly the updated URL for the ontology.

**Comment by egonw** [comment]
Fixed.
