### ISSUE TITLE
[TERM REQUEST] TED-GC/MS 

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#293]
**What would you use as label or labels for the terms?**
TED-GC/MS 

**What is the definition of the term?**
Thermal Extraction and –Desorption-GC/MS (TED-GC/MS)
TED-GC/MS combines Thermogravimetric analysis (TGA) with GC/MS-based chemical analysis of the polymer breakdown products formed during the TGA process

**Is there an ontology that has this term?**
not aware of; 
there are separate terms for TGA and GC/MS (Gas Chromatography/Mass Spectroscopy)

**Additional context**
https://www.gerstel.com/en/TED-GCMS.htm
https://www.osti.gov/pages/servlets/purl/1492387

**Comment by jmillanacosta** [comment]
@vedina I believe this is it http://purl.obolibrary.org/obo/CHMO_0002640



Preferred Name | thermal desorption-gas chromatography mass spectrometry |  
-- | -- | --
Synonyms | TD/GC/MS TD GC/MS TD-GC-MS TD/GC-MS TD-GCMS thermal desorption GC-MS TD GC-MS thermodesorption-gas chromatography mass spectrometry thermodesorption GC-MS TD-GC/MS thermal desorption gas chromatography mass spectrometry thermodesorption GC/MS thermal desorption GC/MS |  
Definitions | A method where a sample mixture is first adsorbed onto packed tubes  (e.g. Tenax) then moved into a desorption oven and heated (100–280 °C  for 5–20 min) to promote thermal desorption of the mixture into the  headspace of the tube. The headspace is sampled and used for gas  chromatography and the eluent is then ionised and characterised  according to mass-to-charge ratio and relative abundance.

Already in the ontology https://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0002640&jump_to_nav=true
