### ISSUE TITLE
typo in Genotoxicity term

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#296]
https://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=http%3A%2F%2Fpurl.enanomapper.org%2Fonto%2FENM_0000039

Genotoxitiy
--

**Comment by egonw** [comment]
Fixed in https://github.com/enanomapper/ontologies/commit/46bc8eb6a220194838224dbf1334bbeb2de5ed1e
