### ISSUE TITLE
add PubMedCentral ID

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#300]

**Comment by DeniseSl22** [comment]
Could you explain this issue in more detail please, @egonw ?

**Comment by DeniseSl22** [comment]
@egonw , I checked for the "regular" pubmed ID, which is already included in the ontology. I will use this as an example to add the PubMed central ID (and maybe DOI should also be considered?). However, the regular PMID now falls under "chemical database identifiers", which I don't think it is strictly speaking; maybe we should consider adding a "literature database identifier" as a superclass (at the same level as chemical database identifier), so make the difference more clear (or would that overcomplicate matters?)

![image](https://user-images.githubusercontent.com/26277832/161237407-3ffa8efe-c713-4e06-a737-ab2461a08ecc.png)
