### ISSUE TITLE
[TERM REQUEST] Sodium dodecyl sulfate polyacrylamide gel electrophoresis (SDS-PAGE) assay

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#305]
**What would you use as label or labels for the terms?**
Sodium dodecyl sulfate polyacrylamide gel electrophoresis (SDS-PAGE) assay

**What is the definition of the term?**
see Harmonizer.

**Is there an ontology that has this term?**
No, but subclass of http://www.bioassayontology.org/bao#BAO_0010019

**Additional context**
See https://terminology-harmonizer.greendecision.eu/NSC-Terminology/Bio-nano%20interactions/Protein%20binding%20assays/SDS-PAGE

**Comment by jmillanacosta** [comment]
@egonw do I need to be given access to see the harmonizer site?

**Comment by egonw** [comment]
> @egonw do I need to be given access to see the harmonizer site?

ah, yes! Do that here with "sign up": https://terminology-harmonizer.greendecision.eu/login

**Comment by jmillanacosta** [comment]
Need to add  http://www.bioassayontology.org/bao#BAO_0010019 (PAGE)
