### ISSUE TITLE
[TERM REQUEST] **cobalt ferrite**

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#307]
**What would you use as label or labels for the terms?**
Cobalt ferrite

**What is the definition of the term?**
CoFe2O4

**Is there an ontology that has this term?**
[http://purl.bioontology.org/ontology/MESH/C569492](https://bioportal.bioontology.org/ontologies/MESH?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FC569492)

**Additional context**
https://pubs.acs.org/doi/10.1021/acsnano.9b08818

**Comment by egonw** [comment]
@vedina, which project is this from, also HARMLESS?
