### ISSUE TITLE
[TERM REQUEST] Temperature programmed surface reaction spectroscopy (TPSR) 

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#310]
**What would you use as label or labels for the terms?**
 Temperature programmed surface reaction spectroscopy (TPSR) 

**What is the definition of the term?**
Temperature programmed surface reaction spectroscopy (TPSR) is a technique to determine the surface chemistry of bulk metal, supported metal, bulk metal oxide, supported metal oxide, zeolite, and molecular sieve catalysts.

**Is there an ontology that has this term?**
not that I am aware of

**Additional context**
 https://doi.org/10.1002/cjce.23913

**Comment by DeniseSl22** [comment]
@jmillanacosta

**Comment by jmillanacosta** [comment]
@DeniseSl22 can you close this issue with the addition of the term to the CHMO ontology? https://github.com/rsc-ontologies/rsc-cmo/pull/20

**Comment by jmillanacosta** [comment]
@egonw @vedina I added the term to the CHMO ontology with https://github.com/rsc-ontologies/rsc-cmo/commit/1135f51da0cbfeb8533867a655f6e8c607572673, will ask you to close the issue after I make the import to eNM.

```
[Term]
id: CHMO:0002928
name: temperature-programmed surface reaction spectroscopy
def: "Spectroscopy that uses thermal analysis to probe the surface chemistry of heterogeneous catalysts." []
synonym: "temperature programmed surface reaction spectroscopy" EXACT []
synonym: "TPSR" EXACT []
is_a: CHMO:0000228 ! spectroscopy
is_a: CHMO:0000681 ! thermal analysis
created_by: http://orcid.org/0000-0002-4166-7093

```

**Comment by vedina** [comment]
thanks!
