### ISSUE TITLE
Label issues NanoReg project

### ISSUE THREAD

**Issue by DeniseSl22** [enanomapper/ontologies#321]
![image](https://user-images.githubusercontent.com/26277832/161260044-c0a68ed7-7157-4955-aebc-42457bc1c1f6.png)

@egonw : Check additions for CTA (Cognitive Threath Analytics) with respect to nanoreg project.
https://github.com/enanomapper/ontologies/commit/ed74b7578ee2641037dfc5f4911dc80d1002fd76

@vedina : is this ENM term (http://purl.enanomapper.org/onto/ENM_0000062) used in NanoReg data?

**Comment by vedina** [comment]
CTA is Cell Transformation Assay   , not Cognitive Threat Analytics

**Comment by DeniseSl22** [comment]
> in Nanoreg and other projects CTA is for Cell Transformation Assay , not Cognitive Threat Analytics

AH, that sounds much more logical, thanks for the quick reply!
