### ISSUE TITLE
OWL does not resolve to owl

### ISSUE THREAD

**Issue by cmungall** [enanomapper/ontologies#323]
http://www.enanomapper.net/ontologies/enanomapper.owl

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML+RDFa 1.1//EN"
"http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<!--[if IE 8 ]><html lang="en" dir="ltr" version="HTML+RDFa 1.1"
...
```

What is the canonical URL?

I'm going to use this
https://raw.githubusercontent.com/enanomapper/ontologies/master/enanomapper.owl

But I think it's better to have a URL that is independent of means of delivery

**Comment by egonw** [comment]
Sorry, only seeing this now. I'll check it. Maybe related to https://github.com/enanomapper/ontologies/issues/324

**Comment by egonw** [comment]
@cmungall, did that last link work for you?
