### ISSUE TITLE
enanomapper in bioportal

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#324]
looks pretty weird - is this intentional ?
https://bioportal.bioontology.org/ontologies/ENM/?p=classes&conceptid=root

![image](https://user-images.githubusercontent.com/211190/176534545-fa9ad9cb-a3e4-4c30-af93-241d056d7b60.png)

![image](https://user-images.githubusercontent.com/211190/176534719-a112958d-6d12-4951-9f65-818c3d8b63e8.png)

**Comment by egonw** [comment]
hi, I saw it only last week myself during the NanoWeek 2022. My last edit was fine in my local Protege. I need to debug what is going on.
