### ISSUE TITLE
[TERM REQUEST] Silicon carbide

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#325]
**What would you use as label or labels for the terms?**
Silicon carbide

**What is the definition of the term?**
Silicon carbide

**Is there an ontology that has this term?**
CHEBI_29390

**Additional context**

**Comment by vedina** [comment]
> @vedina, just for completeness, you mean the material here? Or do you want a term for a nanomaterial based on this material?

according to the data I have it's not nano (> 100 nm DLS size)

**Comment by egonw** [comment]
Fixed with https://github.com/enanomapper/ontologies/commit/122854720b1111f75ff3612fbfdcecc6767d8f4d
