### ISSUE TITLE
include the complete list of crystallinity types

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#33]
triclinic, etc, -> all of them, not a subset.

Related, anatase/rutile are different; the first is a mixture of crystallinity types for TiO2.

**Comment by fehrhart** [comment]
Crystal system, Brevais lattice, Space group, Miller indices  from UDS?

**Comment by vedina** [comment]
Yes, but perhaps there are already crystallography ontologies to be reused ?  These certainly are used in crystallografy databases like COD.

**Comment by fehrhart** [comment]
Triclinic - no
Monoclinic - no
Orthorhombic - no
Tetragonal - no 
Hexagonal-Trigonal - hexagonal not in sense of crystal structure
Hexagonal-Hexagonal - no 
Cubic - not in the sense of crystal structure
Brevais lattice - no
Space group - no
Miller index - no

I will ask also Gareth to check this but as far as I can see there is no existing ontology.

**Comment by fehrhart** [comment]
https://www.uwgb.edu/dutchs/symmetry/xlforms.htm

**Comment by fehrhart** [comment]
The following crystal structures are now included in ENM (version 3).
triclinic
monoclinic
orthorhombic
tetragonal
hexagonal-trigonal
hexagonal-hexagonal
cubic
Bravais lattice
space group
miller index
triclinic-pedial
triclinic-pinacoidal
monoclinic-sphenoidal
monoclinic-domatic
monoclinic-prismatic
orthorhombic-sphenoidal
orthorhombic-pyramidal
orthorhombic-bipyramidal
tetragonal-pyramidal
tetragonal-disphenoidal
tetragonal-dipyramidal
tetragonal-trapezoidal
ditetragonal-pyramidal
tetragonal-scalenoidal
ditetragonal-dipyramidal
trigonal-pyramidal
rhombohedral
trigonal-trapezoidal
ditrigonal-pyramidal
ditrigonal-scalahedral
hexagonal-pyramidal
trigonal-dipyramidal
hexagonal-dipyramidal
hexagonal-trapezoidal
dihexagonal-pyramidal
ditrigonal-dipyramidal
dihexagonal-dipyramidal
tetrahedral
hextetrahedral
diploidal
gyroidal
hexoctahedral
