### ISSUE TITLE
draft dependency diagram

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#334]
```mermaid
flowchart LR
  IAO --> BFO
  BAO --> IAO
  BAO --> NPO
  BAO --> OBI
  OBI --> IAO
  OBI --> BFO
  OBI --> NPO
  NPO --> BAO
  NPO --> BFO
  NPO --> CHEBI
  NPO --> CHEMINF
  NPO --> ENM
  NPO --> IAO
  NPO --> OBI
  NPO --> PATO
  NPO --> UO
  CHEBI --> BFO
  CHEBI --> CCONT
  CHEBI --> ENM
  CHEBI --> NPO
  CHEMINF --> ENM
  CHEMINF --> IAO
  CHEMINF --> PATO
  CHEMINF --> BFO
  PATO --> BFO
  PATO --> NPO
  UO --> IAO
  CCONT --> ENVO
  ENVO --> NPO
  ENVO --> CHEBI
  ENVO --> BFO
```

**Comment by jmillanacosta** [comment]
> ```mermaid
> flowchart LR
>   IAO --> BFO
>   BAO --> IAO
>   BAO --> NPO
>   BAO --> OBI
>   OBI --> IAO
>   OBI --> BFO
>   OBI --> NPO
>   NPO --> BAO
>   NPO --> BFO
>   NPO --> CHEBI
>   NPO --> CHEMINF
>   NPO --> ENM
>   NPO --> IAO
>   NPO --> OBI
>   NPO --> PATO
>   NPO --> UO
>   CHEBI --> BFO
>   CHEBI --> CCONT
>   CHEBI --> ENM
>   CHEBI --> NPO
>   CHEMINF --> ENM
>   CHEMINF --> IAO
>   CHEMINF --> PATO
>   CHEMINF --> BFO
>   PATO --> BFO
>   PATO --> NPO
>   UO --> IAO
>   CCONT --> ENVO
>   ENVO --> NPO
>   ENVO --> CHEBI
>   ENVO --> BFO
> ```

![](https://github.com/enanomapper/ontologies/blob/master/assets/dependency_graph.tsv.png?raw=true)

Graph made up of (subject, object) namespace pairs when namespace_subject != namespace_object

@egonw Would it be better to only include the slims?

**Comment by egonw** [comment]
Yes, good idea! That should be much simpler. And with that a good validation

**Comment by jmillanacosta** [comment]
@egonw updated

![](https://github.com/enanomapper/ontologies/blob/master/assets/slims_graph.png?raw=true)
