### ISSUE TITLE
Bad prefixes in enanomapper-full.owl

### ISSUE THREAD

**Issue by jmillanacosta** [enanomapper/ontologies#335]
The result of `robot merge`: https://github.com/enanomapper/ontologies/blob/72097f8b58b5e842f6bc09924d7c7c2ffae6cf23/.github/workflows/robot.yml#L28 renders weird (repeated?) prefixes in the resulting owl file, [enanomapper-full.owl](https://github.com/enanomapper/ontologies/releases/download/v9.0/enanomapper-full.owl). Just realized this when working on #334 (which will be solved as soon as this is solved).

Snippet of the weird prefixes:
```xml
     xmlns:chebi12="http://purl.obolibrary.org/obo/chebi#"
     xmlns:chebi18="http://purl.obolibrary.org/obo/chebi#2"
     xmlns:chebi19="http://purl.obolibrary.org/obo/chebi#3"
     xmlns:chebi20="http://purl.obolibrary.org/obo/chebi#1"
     xmlns:npo-ext9="http://purl.enanomapper.net/onto/internal/npo-ext.owl#"
     xmlns:cheminf10="http://www.semanticweb.org/ontologies/cheminf.owl#"
     xmlns:npo-ext13="http://purl.enanomapper.net/onto/internal/npo-ext.owl/"
     xmlns:oboInOwl2="ttp://www.geneontology.org/formats/oboInOwl#"
     xmlns:oboInOwl11="oboInOwl:"
```

**Comment by egonw** [comment]
fascinating... I need to have a closer look at this.

**Comment by jmillanacosta** [comment]
> fascinating... I need to have a closer look at this. First thought: in the end, a prefix is just a shortcut; if detected automatically, it's just a max common starting string... particularly these are really weird:
> 
> ```
>      xmlns:chebi12="http://purl.obolibrary.org/obo/chebi#"
>      xmlns:chebi18="http://purl.obolibrary.org/obo/chebi#2"
>      xmlns:chebi19="http://purl.obolibrary.org/obo/chebi#3"
>      xmlns:chebi20="http://purl.obolibrary.org/obo/chebi#1"
> ```

Indeed, happens with bao, cl, obo (/core), enm, skos, chebi, npo... Working on it today

**Comment by jmillanacosta** [comment]
Source of the problem: 
![image](https://user-images.githubusercontent.com/83466805/211507486-614dd67b-0cca-4fe6-9877-561cefd8c40a.png)

**Comment by jmillanacosta** [comment]
Get all the wrong IRIs, and grep import by import to see the source

**Comment by jmillanacosta** [comment]
All error "IRI"s and their source

Now I need to see when they are generated or why they get picked up by `robot merge` as distinct...
 
<!DOCTYPE html>



error_iri | source
-- | --
http://purl.obolibrary.org/obo/cl#3 | uberon-slim.owl
http://purl.obolibrary.org/obo/cl#2 | uberon-slim.owl
http://purl.obolibrary.org/obo/cl#1 | uberon-slim.owl
http://www.bioassayontology.org/bao/# | bao-slim.owl
http://purl.obolibrary.org/obo# | aopo-slim.owl
http://purl.obolibrary.org/obo# | efo-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ | aopo-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ | clo-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ | go-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ | pato-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ | uberon-slim.owl
http://purl.enanomapper.net/onto/ | aopo-slim.owl
http://purl.enanomapper.net/onto/ | bao-slim.owl
http://purl.enanomapper.net/onto/ | bfo-slim.owl
http://purl.enanomapper.net/onto/ | bto-slim.owl
http://purl.enanomapper.net/onto/ | catalog-v001.xml
http://purl.enanomapper.net/onto/ | ccont-slim.owl
http://purl.enanomapper.net/onto/ | chebi-slim.owl
http://purl.enanomapper.net/onto/ | cheminf-slim.owl
http://purl.enanomapper.net/onto/ | chmo-slim.owl
http://purl.enanomapper.net/onto/ | clo-slim.owl
http://purl.enanomapper.net/onto/ | efo-slim.owl
http://purl.enanomapper.net/onto/ | envo-slim.owl
http://purl.enanomapper.net/onto/ | fabio-slim.owl
http://purl.enanomapper.net/onto/ | go-slim.owl
http://purl.enanomapper.net/onto/ | iao-slim.owl
http://purl.enanomapper.net/onto/ | ncit-slim.owl
http://purl.enanomapper.net/onto/ | npo-slim.owl
http://purl.enanomapper.net/onto/ | oae-slim.owl
http://purl.enanomapper.net/onto/ | obcs-slim.owl
http://purl.enanomapper.net/onto/ | obi-slim.owl
http://purl.enanomapper.net/onto/ | pato-slim.owl
http://purl.enanomapper.net/onto/ | sio-slim.owl
http://purl.enanomapper.net/onto/ | uberon-slim.owl
http://purl.enanomapper.net/onto/ | uo-slim.owl
http://www.bioassayontology.org/bao# | aopo-slim.owl
http://www.bioassayontology.org/bao# | bao-slim.owl
http://www.bioassayontology.org/bao# | bao-slim-prop.owl
http://www.bioassayontology.org/bao# | chmo-slim.owl
http://www.bioassayontology.org/bao# | ncit-slim.owl
http://www.bioassayontology.org/bao# | npo-slim.owl
http://purl.obolibrary.org/obo/core# | oae-slim.owl
http://purl.obolibrary.org/obo/hsapdv# | aopo-slim.owl
http://purl.enanomapper.org/onto/ | catalog-v001.xml
http://purl.enanomapper.org/onto/ | chebi-slim.owl
http://purl.enanomapper.org/onto/ | cheminf-slim.owl
http://purl.enanomapper.org/onto/ | npo-slim.owl
http://purl.enanomapper.org/onto/ | ontology-metadata-slim.owl
http://www.w3.org/2008/05/skos# | fabio-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.org/dc/terms/ | clo-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.org/dc/terms/ | go-slim.owl
http://www.geneontology.org/formats/oboInOwl#http://purl.org/dc/terms/ | pato-slim.owl
http://purl.obolibrary.org/obo/chebi# | aopo-slim.owl
http://purl.obolibrary.org/obo/chebi# | chebi-slim.owl
http://purl.obolibrary.org/obo/chebi# | clo-slim.owl
http://purl.obolibrary.org/obo/chebi# | efo-slim.owl
http://purl.obolibrary.org/obo/chebi# | envo-slim.owl
http://purl.obolibrary.org/obo/chebi# | pato-slim.owl
http://purl.obolibrary.org/obo/chebi# | uberon-slim.owl
http://purl.obolibrary.org/obo/chebi#2 | aopo-slim.owl
http://purl.obolibrary.org/obo/chebi#2 | chebi-slim.owl
http://purl.obolibrary.org/obo/chebi#2 | clo-slim.owl
http://purl.obolibrary.org/obo/chebi#2 | efo-slim.owl
http://purl.obolibrary.org/obo/chebi#2 | pato-slim.owl
http://purl.obolibrary.org/obo/chebi#3 | aopo-slim.owl
http://purl.obolibrary.org/obo/chebi#3 | chebi-slim.owl
http://purl.obolibrary.org/obo/chebi#3 | clo-slim.owl
http://purl.obolibrary.org/obo/chebi#3 | efo-slim.owl
http://purl.obolibrary.org/obo/chebi#3 | pato-slim.owl
http://purl.obolibrary.org/obo/chebi#3 | uberon-slim.owl
http://purl.obolibrary.org/obo/chebi#1 | aopo-slim.owl
http://purl.obolibrary.org/obo/chebi#1 | chebi-slim.owl
http://purl.obolibrary.org/obo/chebi#1 | clo-slim.owl
http://purl.obolibrary.org/obo/chebi#1 | efo-slim.owl
http://purl.obolibrary.org/obo/chebi#1 | pato-slim.owl
http://purl.obolibrary.org/obo/chebi#1 | uberon-slim.owl
  |  
http://www.semanticweb.org/ontologies/cheminf.owl# | cheminf-slim.owl
  |  
ttp://www.geneontology.org/formats/oboInOwl# | aopo-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | bao-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | bfo-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | bto-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | ccont-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | chebi-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | cheminf-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | chmo-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | clo-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | efo-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | envo-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | fabio-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | go-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | iao-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | ncit-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | npo-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | oae-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | obcs-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | obi-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | ontology-metadata-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | pato-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | sio-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | uberon-slim.owl
ttp://www.geneontology.org/formats/oboInOwl# | uo-slim.owl
oboInOwl: | aopo-slim.owl
oboInOwl: | bao-slim.owl
oboInOwl: | bfo-slim.owl
oboInOwl: | bto-slim.owl
oboInOwl: | ccont-slim.owl
oboInOwl: | chebi-slim.owl
oboInOwl: | cheminf-slim.owl
oboInOwl: | chmo-slim.owl
oboInOwl: | clo-slim.owl
oboInOwl: | efo-slim.owl
oboInOwl: | envo-slim.owl
oboInOwl: | fabio-slim.owl
oboInOwl: | go-slim.owl
oboInOwl: | iao-slim.owl
oboInOwl: | ncit-slim.owl
oboInOwl: | npo-slim.owl
oboInOwl: | oae-slim.owl
oboInOwl: | obcs-slim.owl
oboInOwl: | obi-slim.owl
oboInOwl: | pato-slim.owl
oboInOwl: | sio-slim.owl
oboInOwl: | uberon-slim.owl
oboInOwl: | uo-slim.owl

**Comment by jmillanacosta** [comment]
> All error "IRI"s and their source
> 
> Now I need to see when they are generated or why they get picked up by `robot merge` as distinct...
> error_iri 	source
> http://purl.obolibrary.org/obo/cl#3 	uberon-slim.owl
> http://purl.obolibrary.org/obo/cl#2 	uberon-slim.owl
> http://purl.obolibrary.org/obo/cl#1 	uberon-slim.owl
> http://www.bioassayontology.org/bao/# 	bao-slim.owl
> http://purl.obolibrary.org/obo# 	aopo-slim.owl
> http://purl.obolibrary.org/obo# 	efo-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ 	aopo-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ 	clo-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ 	go-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ 	pato-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/ 	uberon-slim.owl
> http://purl.enanomapper.net/onto/ 	aopo-slim.owl
> http://purl.enanomapper.net/onto/ 	bao-slim.owl
> http://purl.enanomapper.net/onto/ 	bfo-slim.owl
> http://purl.enanomapper.net/onto/ 	bto-slim.owl
> http://purl.enanomapper.net/onto/ 	catalog-v001.xml
> http://purl.enanomapper.net/onto/ 	ccont-slim.owl
> http://purl.enanomapper.net/onto/ 	chebi-slim.owl
> http://purl.enanomapper.net/onto/ 	cheminf-slim.owl
> http://purl.enanomapper.net/onto/ 	chmo-slim.owl
> http://purl.enanomapper.net/onto/ 	clo-slim.owl
> http://purl.enanomapper.net/onto/ 	efo-slim.owl
> http://purl.enanomapper.net/onto/ 	envo-slim.owl
> http://purl.enanomapper.net/onto/ 	fabio-slim.owl
> http://purl.enanomapper.net/onto/ 	go-slim.owl
> http://purl.enanomapper.net/onto/ 	iao-slim.owl
> http://purl.enanomapper.net/onto/ 	ncit-slim.owl
> http://purl.enanomapper.net/onto/ 	npo-slim.owl
> http://purl.enanomapper.net/onto/ 	oae-slim.owl
> http://purl.enanomapper.net/onto/ 	obcs-slim.owl
> http://purl.enanomapper.net/onto/ 	obi-slim.owl
> http://purl.enanomapper.net/onto/ 	pato-slim.owl
> http://purl.enanomapper.net/onto/ 	sio-slim.owl
> http://purl.enanomapper.net/onto/ 	uberon-slim.owl
> http://purl.enanomapper.net/onto/ 	uo-slim.owl
> http://www.bioassayontology.org/bao# 	aopo-slim.owl
> http://www.bioassayontology.org/bao# 	bao-slim.owl
> http://www.bioassayontology.org/bao# 	bao-slim-prop.owl
> http://www.bioassayontology.org/bao# 	chmo-slim.owl
> http://www.bioassayontology.org/bao# 	ncit-slim.owl
> http://www.bioassayontology.org/bao# 	npo-slim.owl
> http://purl.obolibrary.org/obo/core# 	oae-slim.owl
> http://purl.obolibrary.org/obo/hsapdv# 	aopo-slim.owl
> http://purl.enanomapper.org/onto/ 	catalog-v001.xml
> http://purl.enanomapper.org/onto/ 	chebi-slim.owl
> http://purl.enanomapper.org/onto/ 	cheminf-slim.owl
> http://purl.enanomapper.org/onto/ 	npo-slim.owl
> http://purl.enanomapper.org/onto/ 	ontology-metadata-slim.owl
> http://www.w3.org/2008/05/skos# 	fabio-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.org/dc/terms/ 	clo-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.org/dc/terms/ 	go-slim.owl
> http://www.geneontology.org/formats/oboInOwl#http://purl.org/dc/terms/ 	pato-slim.owl
> http://purl.obolibrary.org/obo/chebi# 	aopo-slim.owl
> http://purl.obolibrary.org/obo/chebi# 	chebi-slim.owl
> http://purl.obolibrary.org/obo/chebi# 	clo-slim.owl
> http://purl.obolibrary.org/obo/chebi# 	efo-slim.owl
> http://purl.obolibrary.org/obo/chebi# 	envo-slim.owl
> http://purl.obolibrary.org/obo/chebi# 	pato-slim.owl
> http://purl.obolibrary.org/obo/chebi# 	uberon-slim.owl
> http://purl.obolibrary.org/obo/chebi#2 	aopo-slim.owl
> http://purl.obolibrary.org/obo/chebi#2 	chebi-slim.owl
> http://purl.obolibrary.org/obo/chebi#2 	clo-slim.owl
> http://purl.obolibrary.org/obo/chebi#2 	efo-slim.owl
> http://purl.obolibrary.org/obo/chebi#2 	pato-slim.owl
> http://purl.obolibrary.org/obo/chebi#3 	aopo-slim.owl
> http://purl.obolibrary.org/obo/chebi#3 	chebi-slim.owl
> http://purl.obolibrary.org/obo/chebi#3 	clo-slim.owl
> http://purl.obolibrary.org/obo/chebi#3 	efo-slim.owl
> http://purl.obolibrary.org/obo/chebi#3 	pato-slim.owl
> http://purl.obolibrary.org/obo/chebi#3 	uberon-slim.owl
> http://purl.obolibrary.org/obo/chebi#1 	aopo-slim.owl
> http://purl.obolibrary.org/obo/chebi#1 	chebi-slim.owl
> http://purl.obolibrary.org/obo/chebi#1 	clo-slim.owl
> http://purl.obolibrary.org/obo/chebi#1 	efo-slim.owl
> http://purl.obolibrary.org/obo/chebi#1 	pato-slim.owl
> http://purl.obolibrary.org/obo/chebi#1 	uberon-slim.owl
>   	 
> http://www.semanticweb.org/ontologies/cheminf.owl# 	cheminf-slim.owl
>   	 
> ttp://www.geneontology.org/formats/oboInOwl# 	aopo-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	bao-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	bfo-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	bto-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	ccont-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	chebi-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	cheminf-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	chmo-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	clo-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	efo-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	envo-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	fabio-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	go-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	iao-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	ncit-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	npo-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	oae-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	obcs-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	obi-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	ontology-metadata-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	pato-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	sio-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	uberon-slim.owl
> ttp://www.geneontology.org/formats/oboInOwl# 	uo-slim.owl
> oboInOwl: 	aopo-slim.owl
> oboInOwl: 	bao-slim.owl
> oboInOwl: 	bfo-slim.owl
> oboInOwl: 	bto-slim.owl
> oboInOwl: 	ccont-slim.owl
> oboInOwl: 	chebi-slim.owl
> oboInOwl: 	cheminf-slim.owl
> oboInOwl: 	chmo-slim.owl
> oboInOwl: 	clo-slim.owl
> oboInOwl: 	efo-slim.owl
> oboInOwl: 	envo-slim.owl
> oboInOwl: 	fabio-slim.owl
> oboInOwl: 	go-slim.owl
> oboInOwl: 	iao-slim.owl
> oboInOwl: 	ncit-slim.owl
> oboInOwl: 	npo-slim.owl
> oboInOwl: 	oae-slim.owl
> oboInOwl: 	obcs-slim.owl
> oboInOwl: 	obi-slim.owl
> oboInOwl: 	pato-slim.owl
> oboInOwl: 	sio-slim.owl
> oboInOwl: 	uberon-slim.owl
> oboInOwl: 	uo-slim.owl

@egonw all these prefixes seem to be slimmer bugs, totally independent from `robot merge`. Looking at `external/uberon` from before I started committing: https://github.com/enanomapper/ontologies/blob/19b1b95a9107122569c9d847f918d8e04cb2d84f/external/uberon-slim.owl#L29
we can already see the same sort of bug happening.

Maybe a sign to try moving definitely to robot?

**Comment by egonw** [comment]
Maybe it was an OWLAPI bug?
