### ISSUE TITLE
Incorporation of ontology classes from Exposure Ontology (EXO)?

### ISSUE THREAD

**Issue by RichardLMR** [enanomapper/ontologies#34]
Hi

You may wish to incorporate (parts of) the Exposure Ontology (EXO), which is available from BioPortal?

For example, as far as I can see, the eNanoMapper ontology does not currently have a class for the important concept of "exposure medium" (e.g. the liquid mixture via which nanomaterials are exposed to the cells in in vitro assays).

The Exposure Ontology has was seems to be a suitable class for this: http://purl.obolibrary.org/obo/ExO_0000083

HTH

Richard

**Comment by lrieswijk** [comment]
@RichardLMR Would you only like to have "exposure medium" added to the eNM ontology from the Exposure Ontology or are there more terms?

**Comment by RichardLMR** [comment]
Hi

To the best of my recollection, I did not spot anything other than "exposure medium" which I felt was important to incorporate. However, I did not thoroughly investigate the entire ontology - merely observe that, as far as I could tell, this important concept was not in any other BioPortal hosted ontologies.

Thanks

**Comment by JKChang2015** [comment]
added to iao-ext.owl
891414c27d47c4ac6abe7e484bf84a7887bda5ae
