### ISSUE TITLE
Typo in BAO ontology description

### ISSUE THREAD

**Issue by filipd** [enanomapper/ontologies#35]
In the following entry: http://aber-owl.net/ontology/ENM#!http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0000015
there is a typo: "a set of instructions, methodology, operations, required reagents, instruments to **carrie** out experiments".

**Comment by egonw** [comment]
Linda, can you contact Stephan Schurer? You can find his email here: http://bioportal.bioontology.org/ontologies/BAO

**Comment by JKChang2015** [comment]
I've contacted with Schurer to request a modification.

**Comment by linikujp** [comment]
This bug is corrected.

**Comment by egonw** [comment]
@linikujp OK, thank! Now, we need to see here that it properly propagates here... we currently use this version: http://www.bioassayontology.org/bao/bao_complete.owl ... what OWL file URL should we be using that has this fix (for the dev version)? Or has this bugfix already been released?

BTW, please notice the tag... we will likely have assay types that we like seen added, which we are happy to contribute.

**Comment by linikujp** [comment]
It is the file bao_vocabulary_assay.owl, which is imported into bao_complete.owl.
@egonw  We will be very happy to coordinate with you to add your assay types. Please request on BAO issue tracker and we will proceed.
