### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by pennym** [enanomapper/ontologies#36]
Hi

How is the issue of nanomaterial functionality (from an industry/product point of view) addressed in the ontology?
I checked for terms like "functionality" and specific types of functionality, such as antibacterial, but I couldn´t find that.
Is there an existing functionality ontology that could serve as the basis for a nano-specific functionality ontology? Would the chEBI ontology be a good basis? I found others that could be relevant too (e.g. PATO and different medical ontologies), but which one is the best may need to be discussed, or is this discussion already taking place?

Penny

**Comment by vedina** [comment]
In addition to the above, there is a recent EC report on [Nanomaterial's functionality](http://ec.europa.eu/environment/integration/research/newsalert/pdf/nanomaterials_functionality_48si_en.pdf) to consider when defining the term.

**Comment by egonw** [comment]
Functionality would be modeled with (ChEBI) roles, or new (sub)classes...  this is biology oriented; 'antibacterial' is CHEBI:33282 ... so, easily doable...

Regarding non-biological roles, that may be harder... 'scratch resistance' is indeed not really a role, so not entirely sure how to do that... Nina, regarding your points... a role says something about the material's purpose... scratch resistance is close, but not entirely that... it's perhaps a secondary role?

BTW, who cares about scratch resistance for nanomaterials?? I can imagine a role 'scratch resistance increasing', though...

**Comment by egonw** [comment]
@vedina @pennym so, the first step would be to make a list of 'roles'/'functionalities' that we need...

**Comment by vedina** [comment]
@egonw - who cares about `scratch resistance` - those who make anti-scratch coating

**Comment by egonw** [comment]
@vedina sure! but that's not a property of the nanomaterial... that's the feature or perhaps role of a material in which the enm is a component, I guess?

**Comment by vedina** [comment]
@egonw how is that not property, if it can be measured?

**Comment by vedina** [comment]
Another example of `functionality` given as example was [Surface plasmon resonance](https://en.wikipedia.org/wiki/Surface_plasmon_resonance) - IMHO this is again measurable property.

**Comment by egonw** [comment]
@vedina no, that's not what I mean... it *is* a property... if the scratch resistance a property really a property of that few nm coating, or of the full material? Does the adhesion of the nm layer on the rest of the matter not (partly) determine the resistance? My point was just, *what* is it a property of...

**Comment by vedina** [comment]
@egonw yes, making a list is the first step.  A subsequent one would be to define which measurable property is related to the `functionality`.

Random search found this [5. Nanotextiles—Properties, Types, Functionalities and Processes](https://www.ic.gc.ca/eic/site/textiles-textiles.nsf/eng/tx03232.html) , see Table 1.

**Comment by vedina** [comment]
@egonw, agree, `what is it a property of` is The question 
see my point above `is the functionality characteristic of the material or of a product (which may contain multiple materials)`
thinking aloud, if a company produces anti-scratching coatings, they need to measure the property independent on what the film will be later put on, that's it, the company will report `scratch resistance` as a property of the film, no?

**Comment by vedina** [comment]
It seems [UDS](https://zenodo.org/record/20688/files/Uniform_Description_System_Nanomaterials-Published-v01-15-02-01.pdf) uses the terms `properties and functionalities` together, but unfortunately does not include specific lists.

**Comment by pennym** [comment]
Referring to what I just heard from people involved in functionality aspects. A nanomaterial functionality is as much a property of the material as is toxicity and the task is to figure out what physchem property links a nanomaterial to a specific functionality so that eventually the industry can search fro direct links between functionality and toxicity. But to be able to do this, we need the ontology, similarly as we need it for linking toxicity.

**Comment by vedina** [comment]
@pennym don't we mostly use modelling to link between properties and toxicity, rather than ontology ?

**Comment by pennym** [comment]
Well yes, modelling will be done only on the toxicological side. I guess this issue is more related to the future when functionality has in fact been linked to PC properties, maybe by industry themselves...But it is still good to keep this in mind already now and including it in the ontology will make it more useful to the industry too and not only tox-researchers. Or is this out of scope?

**Comment by vedina** [comment]
Yes, you are right,  in ontology one adds facts, e.g. if a link between properties and functionality or toxicity is already known. Hence, it's definitely not out of scope.

If the link is not yet established (or perhaps is more complex that a fact that can be added in ontology) then we turn to modelling.

**Comment by pennym** [comment]
Yes, and I guess some functionality aspects are already known, such as Cu or Ag ion solubility being antibacterial etc. I guess for the ontology, a list of relevant functionalities (from the product development point of view) from the industry would be very good to have.

**Comment by fehrhart** [comment]
We intend to add chebi application ontology. role -> application
http://www.ebi.ac.uk/ontology-lookup/browse.do?ontName=CHEBI

Opinions?

**Comment by pennym** [comment]
Looks like a good idea!

**Comment by fehrhart** [comment]
done
