### ISSUE TITLE
Using semantic science integrated ontology (SIO)?

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#37]
@fehrhart , @lrieswijk  
While trying to serialize enanomapper database study content using BAO , I've noticed the PubChem assay annotation uses [SIO](http://semanticscience.org/resource/) to define properties as `has-value`, `has-units`, etc. It seems also SIO has properties defined which can be used to describe `value-less-than-something` , etc. which will be very helpful. 
Do we already have such terms in enanomapper ontology, and if not, should we consider adding ones from SIO?

Examples:
* [RDF/XML for https://apps.ideaconsult.net/enmtest/bundle/1/substance](https://apps.ideaconsult.net/enmtest/bundle/1/substance?max=10&media=application%2Frdf%2Bxml) (under dev)
* [PubChem assay annotation using BAO and SIO](https://pubchem.ncbi.nlm.nih.gov/rest/rdf/endpoint/SID170466782_AID743222.html)

Related issue https://github.com/enanomapper/data.enanomapper.net/issues/9

**Comment by helma** [comment]
I would prefer SIO properties over {lo|up}Values and {lo|up}Qualifiers.

**Comment by vedina** [comment]
SIO actually have properties to represent qualifiers and min/max values.

**Comment by fehrhart** [comment]
OK, we will add that one.
