### ISSUE TITLE
Version numbers

### ISSUE THREAD

**Issue by RichardLMR** [enanomapper/ontologies#4]
When releasing the ontology, will there be formal version release numbers e.g. for the "alpha" version currently on BioPortal (http://bioportal.bioontology.org/ontologies/ENM)? (Please excuse me if this point has already been addressed and I have not noticed!) This would facilitate citing and referencing within an ISA-TAB (or ISA-TAB-Nano) Investigation file.

(I may be digressing, but I would point out that - for the purpose of constructing ISA-TAB or ISA-TAB-Nano Investigation files - I would personally interpret the submission number after ".../submissions/..." in the OWL file download link [e.g. http://data.bioontology.org/ontologies/ENM/submissions/1/download?apikey=..... etc.] as the version number if the ontology is available from BioPortal as this seems consistent with the ISA-TAB example files: http://isatab.sourceforge.net/examples.html )

**Comment by jannahastings** [comment]
Hi Richard, thanks for spotting this. We are going to use numeric version numbers, starting today! I just added metadata stating that this is release 1 to the ontology file (which will be picked up by BioPortal downstream) and the repository here. We anticipate a 6-monthly major release cycle with minor increments in between.

**Comment by jannahastings** [comment]
Closing as has been addressed
