### ISSUE TITLE
[TERM REQUEST] perovskite

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#410]
**What would you use as label or labels for the terms?**
perovskite

**What is the definition of the term?**
perovskite

**Is there an ontology that has this term?**

https://bioportal.bioontology.org/ontologies/MESH?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FC059910

https://bioportal.bioontology.org/ontologies/SWEET?p=classes&conceptid=http%3A%2F%2Fsweetontology.net%2FmatrMineral%2FPerovskite

**Additional context**
HARMLESS use case materials

**Comment by vedina** [comment]
I would like to reopen, as perovskite term is not limited to calcium titanium dioxide

https://en.wikipedia.org/wiki/Perovskite_(structure) 
> **A perovskite is any material with a [crystal structure](https://en.wikipedia.org/wiki/Crystal_structure) following the formula ABX3,** which was first discovered as the [mineral called perovskite](https://en.wikipedia.org/wiki/Perovskite), which consists of [calcium titanium oxide](https://en.wikipedia.org/wiki/Calcium_titanium_oxide) (CaTiO3).[[2]](https://en.wikipedia.org/wiki/Perovskite_(structure)#cite_note-Min-2)

The HARMLESS perovskites use cases are NOT  Calcium_titanium_oxide  , and annotating them with the current enanomapper entry is misleading.

**Comment by jmillanacosta** [comment]
> 

Understood. 

Would a class for the quality of 'Perovskite structure' be useful to you (`entity>quality>chemical substance quality>crystal structure>Perovskite`) or would you prefer a  'Perovskite-structured material' `material entity`?

**Comment by vedina** [comment]
I would say `material entity` is more appropriate in this case, as annotation would be for materials.  

But it might be also useful to have entry under crystal structure, to annotate crystal structures (e.g. from experimental data)

**Comment by jmillanacosta** [comment]
> I would say `material entity` is more appropriate in this case, as annotation would be for materials.
> 
> But it might be also useful to have entry under crystal structure, to annotate crystal structures (e.g. from experimental data)

Understood, will make the necessary changes
