### ISSUE TITLE
move palladium nanoparticle	

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/ontologies#43]
http://purl.obolibrary.org/obo/CHEBI_52853	palladium nanoparticle	
move from 	
http://purl.obolibrary.org/obo/CHEBI_52855	inorganic nanoparticle
to 	
http://purl.bioontology.org/ontology/npo#NPO_1384   metal nanoparticle

**Comment by egonw** [comment]
Freddie, can you convert this into a patch and make a pull request?
