### ISSUE TITLE
move platinum nanoparticle	

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/ontologies#44]
http://purl.obolibrary.org/obo/CHEBI_50831	platinum nanoparticle	
move from 	
http://purl.obolibrary.org/obo/CHEBI_52855	inorganic nanoparticle
to 	
http://purl.bioontology.org/ontology/npo#NPO_1384    metal nanoparticle

**Comment by egonw** [comment]
Fixed by commit https://github.com/enanomapper/slimmer/commit/59b4cbea76722a35c5e310052a4f22b69ab4bc44
