### ISSUE TITLE
add several nanoparticle ontologies

### ISSUE THREAD

**Issue by fehrhart** [enanomapper/ontologies#45]
These items are not yet covered by any ontology: 
copper nanoparticle 
zirconium dioxide nanoparticle 
fullerenol nanoparticle
polyethylenglycol nanoparticle
germanium nanoparticle 
molybdenum trioxide nanoparticle 
aluminum nanoparticle
cadmium(II) oxide nanoparticle
Manganese (IV) dioxide nanoparticle 
tungsten nanoparticle
tricalcium phosphate nanoparticle

Some details and information (sheet 3): 

https://docs.google.com/spreadsheets/d/1CeAjmJFqjrLD14GNphjaCSUlaTaSwHfV91MA4e5oi4M/edit?usp=sharing

**Comment by G-Owen** [comment]
I am doubtful about the zirconium oxide and zirconium dioxide nanoparticles as being separate entities. 'Zirconium oxide', 'zirconium dioxide', 'zirconia', and 'zirconic anhydride' are all widely used synonyms for ZrO2

**Comment by fehrhart** [comment]
I checked the material source in the primary literature (Sigma Aldrich # 643025), that is indeed ZrO2 although they keep calling it Zirconium oxide...

**Comment by egonw** [comment]
I have corrected my patch in the NPO (along with creating a 'devel' branch): https://github.com/sobolevnrm/npo/commit/77d34c12562f61ec871adc56cf9be2169b86e81e

Let's start make patches for the remaining nanoparticles in this branch?

**Comment by fehrhart** [comment]
done
