### ISSUE TITLE
annotation for THP.1 cells

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#46]
I'm looking for ontology annotation of

`Phorbol 12-myristate 13-acetate transformed  THP.1 cells (Human monocyte derived macrophages)`

cc @lrieswijk @egonw

**Comment by egonw** [comment]
@vedina how do you like to use the annotation? Do you want to make an "is-a" statement? At what level? That is, do we need a new URI or would typing the cells as "THP.1 cell" work?

@fehrhart what is the biological/experimental reason for the transformation? Is this specific for this experiment, e.g. to create the "right" conditions? Would people want to search/query based on a particular transformation?

**Comment by fehrhart** [comment]
These cells are actually THP-1 cells:  http://www.ebi.ac.uk/efo/EFO_0001253
After treatment with this phorbol ester (TPA or PMA, http://purl.obolibrary.org/obo/CHEBI_37537) the cells start differentiation and gain some macrophage like properties (ontology of this induced cellular change: http://purl.obolibrary.org/obo/GO_1904628).
@ Egon  I suppose they are used as an in vitro model for macrophages.

**Comment by vedina** [comment]
The goal is to annotate the specific experiment, using these transformed cells. I'll ask the researcher doing the experiment to comment on biology.

**Comment by egonw** [comment]
OK, then it sounds to me, the treatment is just part of the experimental protocol and nothing to do with bioloical type differentiation. Nina, that means that the EFO_0001253 URI should do fine, me thinks!

**Comment by egonw** [comment]
@fehrhart given the bug is closed, that implies that this EFO term is already part of our ontology?

**Comment by fehrhart** [comment]
Yes, it is.
The other terms may be needed to describe the experiment, the pre-treatment of the cells, res.
