### ISSUE TITLE
online hackathons for ontology development

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#47]
Hi all, (@JKChang2015 @G-Owen @lrieswijk @vedina @fehrhart)

we now have a steady flow of ontology requests, but not enough people making patches. I think we should have a number of very technical, hands-on, online hackathon meetings with the WP2 and WP3 people (probably also WP4/WP5 as use case owners) for internal teaching of making patches. We should not longer await what the other is doing, but get our hands dirty, make mistakes, confront upstream, and learn.

I rather have this meeting inclusive (the more people, the merrier) and more than happy with external people joining, but it seems we need internal education in the first one/two meetings.

The purpose would be educate ourselves, identify road blocks, find best practices, etc, but secondly and importantly, make sure we grow our ontology (and upstream ones). The rate delimiting factor no longer seems to be identifying the right upstream ontologies, but to extend them in a sustainable way.

Please comment here if you like to join, and then we can identify a weekly telcon time. @G-Owen, whom else should we invite from with ENM that we need to join from the start? It should be technical people that will actually and personally make patches.

Egon

**Comment by G-Owen** [comment]
Hello everybody,

Firstly - apologies that it has taken much longer than we ever 
anticipated to get the ontology development moving again at the EMBL-EBI 
end. Hopefully a 'handover meeting' with Janna soon help sort out a lot 
of the 'silly' issues that have got in the way.

A weekly teleconference sounds like a good idea to me. Let's talk more 
in Brussels.

Gareth


On 22/01/2016 09:37, Egon Willighⓐgen 0000-0001-7542-0286 wrote:
>
> Hi all, (@JKChang2015 <https://github.com/JKChang2015> @G-Owen 
> <https://github.com/G-Owen> @lrieswijk <https://github.com/lrieswijk> 
> @vedina <https://github.com/vedina> @fehrhart 
> <https://github.com/fehrhart>)
>
> we now have a steady flow of ontology requests, but not enough people 
> making patches. I think we should have a number of very technical, 
> hands-on, online hackathon meetings with the WP2 and WP3 people 
> (probably also WP4/WP5 as use case owners) for internal teaching of 
> making patches. We should not longer await what the other is doing, 
> but get our hands dirty, make mistakes, confront upstream, and learn.
>
> I rather have this meeting inclusive (the more people, the merrier) 
> and more than happy with external people joining, but it seems we need 
> internal education in the first one/two meetings.
>
> The purpose would be educate ourselves, identify road blocks, find 
> best practices, etc, but secondly and importantly, make sure we grow 
> our ontology (and upstream ones). The rate delimiting factor no longer 
> seems to be identifying the right upstream ontologies, but to extend 
> them in a sustainable way.
>
> Please comment here if you like to join, and then we can identify a 
> weekly telcon time. @G-Owen <https://github.com/G-Owen>, whom else 
> should we invite from with ENM that we need to join from the start? It 
> should be technical people that will actually and personally make patches.
>
> Egon
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/enanomapper/ontologies/issues/47>.
>

-- 
ChEBI team,
European Bioinformatics Institute (EMBL-EBI),
European Molecular Biology Laboratory,
Wellcome Trust Genome Campus,
Hinxton, Cambridge,
CB10 1SD, United Kingdom

**Comment by fehrhart** [comment]
Please fill in the doodle for finding a weekly time slot for working on the
eNM ontology.

Best regards,
Freddie

http://doodle.com/poll/tm8eawnebhrn97xa
