### ISSUE TITLE
BFO_0000001 does not have description

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#5]
http://purl.obolibrary.org/obo/BFO_0000001

Does not have a description.

**Comment by jannahastings** [comment]
The problem is at the source -- the classes-only variant of BFO in OWL. I have written to the creator of that variant to see if it can be addressed.

**Comment by jannahastings** [comment]
Actually, no I take that back. The annotations are there, there is no definition for this class but there are IAO metadata property annotations such as 'elucidation' and 'example of usage'. Still a mystery why these do not get imported...

**Comment by jannahastings** [comment]
... I believe I was working from the wrong import source file. The correct file is that found at http://purl.obolibrary.org/obo/bfo/classes-only.owl. I have changed the .props and now I get no output in Jenkins. Does something else in the settings need to change other than the .props file?

**Comment by jannahastings** [comment]
I have resolved this now.
