### ISSUE TITLE
nanomaterial types from caNanoLab

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#50]
- Biopolymer NPO_882 (not in ENM?)
- CarbonNanotube  NPO_606
- DWNT	NPO_301
- Dendrimer	NPO_735
- Emulsion	ENVO_00010506
- Fullerene	CHEBI_33416
- Liposome	NPO_719  (not in ENM?)
- MWNT	NPO_112
- MetalParticle	NPO_1384
- Polymer	CHEBI_60027  (not in ENM ?)
- QuantumDot	NPO_589
- SWNT	NPO_157
- carbon	[caNanoLab entry, likely carbon nanotube NPO_606](https://cananolab.nci.nih.gov/caNanoLab/#/sample?sampleId=6979623&fromKeyword=true)
- carbon black	CHEBI_82297  (not in ENM)
- metal oxide	NPO_1541
- metalloid	 NPO_755 (not in ENM)
- nanobin	 ?
- nanohorn	NPO_457
- nanolipogel	 ?
- nanorod	NPO_122
- nanoshell	NPO_270
- silica	NPO_1373

Some are missing in ENM (or I couldn't find)

**Comment by vedina** [comment]
Just found this mapping exist already http://www.nano-ontology.org/mappings/cananolab-to-npo-mappings

**Comment by G-Owen** [comment]
I recall that **germanium nanoparticle** (not in NPO) is in an earlier request. **Metalloid**, or better still **metalloid nanoparticle**, would be a better parent term for it  than the one originally suggested (metal nanoparticle).

**Comment by fehrhart** [comment]
To be added: 
biopolymer (http://purl.org/obo/owl/CHEBI#CHEBI_33694)
liposome (http://purl.bioontology.org/ontology/npo#NPO_719)
polymer (http://purl.obolibrary.org/obo/CHEBI_60027)
carbon black (http://purl.obolibrary.org/obo/CHEBI_82297)
metalloid (http://purl.bioontology.org/ontology/npo#NPO_755)

no term found:
nanobin
nanolipogel

**Comment by fehrhart** [comment]
Jiakang will write nanoparticle ontologies for these materials
biopolymer (http://purl.org/obo/owl/CHEBI#CHEBI_33694)
carbon black (http://purl.obolibrary.org/obo/CHEBI_82297)
metalloid (http://purl.bioontology.org/ontology/npo#NPO_755)
alloy http://sweet.jpl.nasa.gov/2.3/matrIndustrial.owl#Alloy
nanobin
nanolipogel
