### ISSUE TITLE
[TERM REQUEST] CeO2/Co3O4 nanoparticle

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#503]
**What would you use as label or labels for the terms?**
Annotate a dataset: https://zenodo.org/records/7989699

Quote:

`CeO2/Co3O4 nanoparticles were provided by Promethean Particles (EMR identifier in the project: ERM00000397).`

**What is the definition of the term?**
Not sure.

**Is there an ontology that has this term?**
ENM and NPO both don't seem to have it.

**Comment by jmillanacosta** [comment]
Synonyms (from its safety sheet "CeO2 Co3O4 -SDS.pdf"):
- `CeO2/Co3O4 nanoparticle`
- `Cerium(IV)/Cobalt(II,III)`
- `Tricobalt tetraoxide/cerium dioxide/ceria`


Definition from its safety data sheet: 
> Cerium(IV)/Cobalt(II,III) mixture of oxide nanoparticles (in aqueous dispersion)

We have no clear way of modelling mixtures in the eNanoMapper. There is a `mixture` class (http://purl.obolibrary.org/obo/CHEBI_60004), a `cerium oxide nanoparticle` class (http://purl.enanomapper.org/onto/ENM_9000006), and a `cobalt oxide nanoparticle class` (http://purl.enanomapper.org/onto/ENM_0000119).

Possible solutions:
- **A**: `CeO2/Co3O4 nanoparticle`: `subClassOf(mixture)`, `subClassOf(cerium oxide nanoparticle)`, `subClassOf(cobalt oxide nanoparticle class)`. Simply state that it is a kind of all three, simple solution.
- **B**: `CeO2/Co3O4 nanoparticle`: `subClassOf(mixture)`, `sameAs (has_part some CeO2, has_part some Co3O4)`, more expressive but also more complicated than the rest of similar classes in eNMO.

If we think of an approach like **B** it would be more in line with the plans to make the ontology more expressive.

@egonw thoughts? Maybe we can use **A** for now, but ideally move to **B** as we start defining the architectural ontology design patterns for all types of nanoparticles, nanoparticle mixtures, nanocomposites, nanomaterials, nanoobjects; if that's something we want to (or can) do.

**Comment by egonw** [comment]
Nice discussion for Feb 8!
