### ISSUE TITLE
nanomaterial types from NanoWiki

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#51]
Consider adding [Alloy](http://bioportal.bioontology.org/ontologies/MATR?p=classes&conceptid=http%3A%2F%2Fsweet.jpl.nasa.gov%2F2.3%2FmatrIndustrial.owl%23Alloy)

Could you confirm CB material from this [paper](http://pubs.rsc.org/en/Content/ArticleLanding/2014/FD/C4FD00117F#!divAbstract) is carbon black (CHEBI_82297) ?

The new NanoWiki content has entries for `asbestos` and `Glass wool` without types assigned - what would be the correct term for these?

**Comment by fehrhart** [comment]
No, the carbon containing material in the paper is this one:

![schiff base ligand h2l](https://cloud.githubusercontent.com/assets/11389574/13221237/a0b48a76-d97a-11e5-8e43-a781f78ebb0a.jpg)

**Comment by vedina** [comment]
Thanks @fehrhart !

@egonw - is it possible to add SMILES for this compound in NanoWiki ?

**Comment by fehrhart** [comment]
Is asbestos and glass wool supposed to be nanomaterials or non-nano reference materials?

**Comment by pennym** [comment]
They are counted as "non-nano" reference materials. Info for them can be found in FigShare: https://figshare.com/articles/Tox_and_physchem_data_miRNAno_xlsx/2198986

**Comment by fehrhart** [comment]
Added asbestos and glass wool to ENM.
