### ISSUE TITLE
Metal oxide NPO_1541 instead of NPO_1540

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#52]
Could you please check, in [ENM ontology](http://bioportal.bioontology.org/ontologies/ENM) `metal oxide` is NPO_1541, while in BioPortal it resolves to NPO_1540

**Comment by fehrhart** [comment]
NPO_1540 refers to 'metal oxide' (http://purl.bioontology.org/ontology/npo#NPO_1540) an oxide of metal while NPO_1541 refers to 'metal oxide **nanoparticle**' (http://purl.bioontology.org/ontology/npo#NPO_1541) a **nanoparticle** which is basically composed of a metal oxide.
In ENM we only adopted metal oxide nanoparticle and that is the correct one.
