### ISSUE TITLE
Assay types from public MODENA data

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#53]
Assay types
- ATP BAO_0010001  (in ENM)
- LDH  NPO_1709 (in ENM)
- MTT NPO_1911
- WST-1  CSEO_00001572,

**Comment by fehrhart** [comment]
What is it with that assays? What shall we do about them?

**Comment by vedina** [comment]
The last two are not in the ENM ontology, would be nice to be added (if not already).

**Comment by fehrhart** [comment]
Ah, ok. 
MTT is now added, WST-1 will be added to the BAO soon (and then to ENM).
