### ISSUE TITLE
NanoWiki assays not in BAO

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#55]
The assays in the below screenshot that are subclassing a BAO term should be added to the ENM ontology (and/or eventually the BAO ontology):

![image](https://cloud.githubusercontent.com/assets/26721/13223914/89107d60-d986-11e5-9bd4-72fa25bc4b26.png)

**Comment by JKChang2015** [comment]
5 new terms, 6 existing terms, and **cell viability assay** is already in ENM

**Comment by JKChang2015** [comment]
terms  already in eNM: 
Transcriptional Response Profiling Assay
Toxicity Assay
Oxidative Stress Assay
Genotoxicity Assay
Cytotoxicity Assay
Cell Growth Assay

added terms:
Metabolic Activity Assay
DNA Damage Assay
Cell Membrane Integrity Assay

**Comment by JKChang2015** [comment]
solved
