### ISSUE TITLE
Different URI namings

### ISSUE THREAD

**Issue by rautenberg** [enanomapper/ontologies#56]
There are **http://purl.enanomapper.org/onto**/ENM_000.. for enpoint URIs
but a
<!ENTITY resource "http://purl.enanomapper.net/php/" > 
with resulting **http://purl.enanomapper.net/php**/NM_00... URIs defined at
https://github.com/enanomapper/ontologies/blob/master/internal/descriptors/nm.owl#L16 

can this be standardized to a common URI structure in the different ontology files?

can be: 
http://purl.enanomapper.org/onto/
or
https://purl.enanomapper.org/onto/

**Comment by fehrhart** [comment]
@G-Owen , @JKChang2015  
Is this possible/necessary/not recommendable?...

**Comment by JKChang2015** [comment]
solved
