### ISSUE TITLE
move 'metal oxde nanoparticle' to child of 'inorganic nanoparticle'

### ISSUE THREAD

**Issue by G-Owen** [enanomapper/ontologies#58]
metal oxide nanoparticle http://purl.bioontology.org/ontology/npo#NPO_1541 is currently classed as is_a nanoparticle, http://purl.bioontology.org/ontology/npo#NPO_707

It would be better if it was instead classed as is_a inorganic nanoparticle http://purl.obolibrary.org/obo/CHEBI_52855

**Comment by fehrhart** [comment]
agree

**Comment by JKChang2015** [comment]
relocated
