### ISSUE TITLE
Functionality again

### ISSUE THREAD

**Issue by pennym** [enanomapper/ontologies#61]
In NanoREG2 the issue of functionality (or application) is strongly discussed and I wonder whether that part of the ontology should be increased. ECHA has published a guidance on the use of descriptions for chemicals and people within NanoREG 2 are recommending this to be used in relation to a nano database.
http://echa.europa.eu/documents/10162/13632/information_requirements_r12_en.pdf
If you look at the end of the document there is a list of descriptions for technical functions (starting on page 74). Some of them are under application in the eNM ontology, but not all. Should they be added?

**Comment by JKChang2015** [comment]
I added these terms to a spreadsheet. https://docs.google.com/spreadsheets/d/1V68gdSACCRNSD3HdXHcQbGz2sUZQiqlGmjK3L1WBXyY/edit#gid=0

@G-Owen shall we discuss about these new terms?

**Comment by JKChang2015** [comment]
I mapped the new terms to eNM ontology (existing & similar ). Please check it out in the spreadsheet.  @G-Owen

**Comment by JKChang2015** [comment]
added
