### ISSUE TITLE
BioPortal failed to load eNanoMapper (ENM) from URL

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#64]
I got this email from BioPortal:

-----------------------------------------------------------------------------------------------
BioPortal failed to load eNanoMapper (ENM) from URL: http://purl.enanomapper.org/onto/enanomapper.owl.

Please verify the URL you provided for daily loading of your ontology:

    Make sure you are signed in to BioPortal.
    Navigate to your ontology summary page: http://bioportal.bioontology.org/ontologies/ENM.
    Click the "Edit submission information" link.
    In the Location row, verify that you entered a valid URL for daily loading of your ontology in the URL text area. 

If you need further assistance, please contact us via the BioPortal support mailing list.

Thank you,
The BioPortal Team 
-----------------------------------------------------------------------------------------------

**Comment by rautenberg** [comment]
The server or network is not reachable, I'm on it.

**Comment by rautenberg** [comment]
is up again and working.
