### ISSUE TITLE
graphene oxide ontology entry

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#65]
Is there one in the ENM ontology? or elsewhere?

(it's a NanoWiki3 entry)

**Comment by JKChang2015** [comment]
Graphene oxide has been submitted to CHEBI database, it will be added to CHEBI ontology in next CHEBI release. 

FYI: https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:132889

**Comment by egonw** [comment]
It seems it's not part of the October release?
