### ISSUE TITLE
The nanomaterial subclass hierarchy in ENM ontology 3.0

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#67]
The nanomaterial subclass hierarchy in the ENM ontology 3.0  (release 05/22/2016) looks weird, 

![image](https://cloud.githubusercontent.com/assets/211190/15984941/d2e3c38e-2fe4-11e6-972f-30d8678c86bf.png)

in particular the Chemical substance (`CHEBI_59999`), and other CHEBI classes doesn't seem to have a parent class (Protege displays these as descendants of `owl:Thing`), while classes for `material entity` are subclasses of `entity`. In [CHEBI](https://bioportal.bioontology.org/ontologies/CHEBI?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_59999) the same class is a subclass of `chemical entity`. 

The rdf/xml file is downloaded from the `RDF/XML` link for 3.0 release [here](https://bioportal.bioontology.org/ontologies/ENM/?p=summary)

cc: @egonw @G-Owen

**Comment by JKChang2015** [comment]
Issue caused by failed to load the CHEBI ontology, now solved.
#68
