### ISSUE TITLE
NM components types (caNanoLab)

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#80]
NM components types - could you help with matching ontology entries.

````
coat
core
excipient
Internal buffer
lipid
modifier
monomer
polymer
repeat unit
shell
````

**Comment by JKChang2015** [comment]
![image](https://cloud.githubusercontent.com/assets/16242098/18990059/6d7fd95e-8707-11e6-8409-0c6ed13f0acb.png)

I matched these terms against our import ontologies.

**Comment by vedina** [comment]
Thanks!
