### ISSUE TITLE
carbon black nanoparticle?

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#81]
There does not seem to be a term for carbon black nanoparticles yet. Like in http://particleandfibretoxicology.biomedcentral.com/articles/10.1186/1743-8977-11-4

ChEBI has "carbon black" but I am not sure at this moment if that is in the right place in the ontology (given NPO has "metal oxide" and "metal oxide nanoparticle") and this term may not be (ontologically) the same as "carbon black nanoparticle"... (and no time to check immediately right now).

**Comment by vedina** [comment]
AFAIK `carbon black` is not necessary nanoparticle

**Comment by egonw** [comment]
In that paper it is sized 14 nm, according to a Visby data set submission by Penny ;)

**Comment by vedina** [comment]
http://carbon-black.org/files/ICBA-Particle-CB-Factsheet-111413.pdf

**Comment by JKChang2015** [comment]
I discussed with Gareth, as Nina mentioned carbon black is not necessary nanoparticle, his suggestion is to add a  **_carbon black nanoparticle_** to a sub-class of **_carbon black_**.

**Comment by egonw** [comment]
Or go all the way how NPO models it... which has "titanium dioxide" and "titanium dioxide nanoparticle" and uses an OWL axiom to link the second to the first...

**Comment by G-Owen** [comment]
ChEBI now has carbon black nanoparticle (CHEBI:133602) which is classified as 
a) is_a carbon black (CHEBI:82297)
b) is_a carbon nanostructure (CHEBI:50812)
c) is_a nanoparticle (CHEBI:50803)

**Comment by JKChang2015** [comment]
has been added. 7f67a5839f3da40bddc9d8cdf6f5cb09e90cfb41
