### ISSUE TITLE
something goes wrong with the classification of a ENM

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#85]
![image](https://cloud.githubusercontent.com/assets/26721/19649857/a6588c2c-9a07-11e6-83c0-5249124e0e2c.png)

**Comment by JKChang2015** [comment]
![image](https://cloud.githubusercontent.com/assets/16242098/19650051/cf507dfe-99ff-11e6-84d1-2bc5cb755e55.png)

It has been corrected (5e427f5db70a983c551514e43df5c0cd62d9e2e1).  It seems not been uploaded to the bio-portal.

**Comment by egonw** [comment]
Oh, thanks for checking! We had a dinner last night, so did not get around to it yet... if it's fixed in the source, we can close this issue.
