### ISSUE TITLE
chemical descriptor under oral toxicity ontology entry

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#88]
There is probably something wrong, as the bioportal version has the `chemical descriptor` tree under `oral toxicity entry`.

![image](https://cloud.githubusercontent.com/assets/211190/19674716/9086b636-9a92-11e6-953b-2d0bff7ce3b5.png)

Apologies if already fixed in the development version

**Comment by JKChang2015** [comment]
Thanks for pointing out. It has been fixed ( 69078219d5c8684622223ec73e1fb3c59bfff0ed). 


![image](https://cloud.githubusercontent.com/assets/16242098/19678231/cdc0a604-9a94-11e6-8e67-7ce7af1ff911.png)

**Comment by vedina** [comment]
Thanks!
