### ISSUE TITLE
Solubility in organic solvents

### ISSUE THREAD

**Issue by vedina** [enanomapper/ontologies#90]
It seems there is no specific entry for `Solubility in organic solvents`, which is an OECD endpoint

https://www.oecd.org/ehs/templates/harmonised-templates-physico-chemical-properties.htm

**Comment by JKChang2015** [comment]
added to npo-ext.owl
FYI: https://github.com/enanomapper/ontologies/commit/d2fe501ac8a3eb5cb54f35dfe339b709d6d307f4#diff-7e4c6bd91d7032f49fb3128df8956239
