### ISSUE TITLE
should silicon dioxide nanoparticle not be subclass of metal oxide nanoparticle

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#95]
It currently does not seem to be:

![image](https://cloud.githubusercontent.com/assets/26721/20639798/49e8562c-b3cd-11e6-8a55-8d6ddfab45d7.png)

**Comment by egonw** [comment]
(and it should not be a subclass of "silicon dioxide", I guess, which is not in line with how the other metal oxide nanoparticles are modeled.

**Comment by JKChang2015** [comment]
close?

**Comment by egonw** [comment]
Yeah, patch looks good to me.

**Comment by egonw** [comment]
Thanks!

**Comment by JKChang2015** [comment]
@G-Owen It has been corrected to subclass of inorganic nanoparticle.
![image](https://cloud.githubusercontent.com/assets/16242098/20673045/65a3cc02-b57b-11e6-9e27-24992240378a.png)

**Comment by egonw** [comment]
@G-Owen, oh, very good point! In nanosciences I tend to see it referred to as a metal oxide... but they can be wrong... I should have realized that when asking it...

There are some further comments here: https://www.researchgate.net/post/Metal_Oxides_vs_Non-Metal_Oxides

**Comment by egonw** [comment]
BTW, the other half of my request was also about the following original inconsistency... "titanium dioxide nanoparticle" in the NPO is not a child of ""titanium dioxide"... which was the case for "silicon dioxide"...

I would not mind a "metalloid oxide nanoparticle" term, but at least have "titanium dioxide nanoparticle" somewhere under nanoparticle..

**Comment by G-Owen** [comment]
Jiakang - in the hierarchy diagram you pasted 40 minutes ago, both copper(II) oxide nanoparticle and titanium dioxide nanoparticle  should be moved under metal oxide nanoparticle.

**Comment by G-Owen** [comment]
As  we have 'metalloid nanoparticle', I guess it makes sense to also have 'metalloid oxide nanoparticle' as a class name, which would have the nanoparticles of any of the (boron, silicon, germanium, arsenic, antimony, or tellurium) oxides..

**Comment by JKChang2015** [comment]
@egonw  OK, will add to eNM ontology.

**Comment by JKChang2015** [comment]
@G-Owen  Since many nanoparticle terms need to be re-located. I created a new issue https://github.com/enanomapper/ontologies/issues/96
