### ISSUE TITLE
nanoparticle classes need to be re-located

### ISSUE THREAD

**Issue by JKChang2015** [enanomapper/ontologies#96]
The classification of nanoparticles are mess up.  need to be re-located
![image](https://cloud.githubusercontent.com/assets/16242098/20675104/15abd502-b583-11e6-8cf5-37abceea1527.png)

**Comment by JKChang2015** [comment]
![image](https://cloud.githubusercontent.com/assets/16242098/20675269/9cf31ebc-b583-11e6-9ca5-8c75859abc61.png)

duplicate classes

**Comment by JKChang2015** [comment]
**metal oxide nanoparticle** Duplicated( has two super-class)

    

    <owl:Class rdf:about="http://purl.bioontology.org/ontology/npo#NPO_1541">
        <rdfs:subClassOf rdf:resource="http://purl.bioontology.org/ontology/npo#NPO_707"/>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/CHEBI_52855"/>
        <npo:code rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NPO_1541</npo:code>
        <npo:preferred_Name rdf:datatype="http://www.w3.org/2001/XMLSchema#string">metal oxide nanoparticle</npo:preferred_Name>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">metal oxide nanoparticle</rdfs:label>
    </owl:Class>

**Comment by JKChang2015** [comment]
duplicated magnetic nanoparticle

![image](https://cloud.githubusercontent.com/assets/16242098/20881772/d668f228-bad5-11e6-943f-4e8957058455.png)

**Comment by fehrhart** [comment]
Magnetite is the common name for an iron oxide Fe3O4 - it is also magnetic
but thats something different than magnetic nanoparticle.

We should think about how to handle that if a material has a property
(magnetic) but also belongs to a chemical class (iron oxide).

Best regards,
Freddie
